#Initialization

In [1]:
import pandas as pd
import numpy as np
#from google.colab import files

# Real Test Data

In [2]:
true = pd.read_csv ('TestingDataCifar10Vgg19Size100.csv')

true

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Class Label
0,-0.406891,2.518248,1.078850,0.542428,-1.991698,3.393651,-2.000609,1.459428,0.544127,8.005242,...,-2.456039,-3.918902,-0.854659,-0.920625,-6.272399,12.150599,-3.211717,4.291994,-1.800023,3
1,2.840969,0.343795,0.027460,1.814588,0.953517,5.074302,0.924205,-2.887625,2.180433,4.635614,...,-1.838858,-0.961226,-0.228185,-3.908548,-3.032962,3.837305,0.023137,5.692143,-1.926771,8
2,4.493119,0.410996,2.371259,1.013259,-4.057048,6.923604,1.012868,-0.229702,-0.866060,6.087259,...,-2.217638,-1.704095,-1.250339,-5.571286,-5.933181,3.077938,-1.398100,3.688967,-1.630913,8
3,3.223652,1.491172,1.007674,-2.064836,-2.347337,0.038917,0.244371,-1.236836,0.512209,1.670135,...,-1.020960,-4.625875,2.174134,-1.645248,-0.435909,3.004525,0.849615,4.051802,-2.424884,0
4,-3.718518,5.119709,-0.553372,-1.777166,1.834947,-0.423276,1.430342,-0.556790,0.415500,1.908716,...,-1.289669,-4.775533,-4.805314,-3.998766,-3.282487,0.145617,-1.016712,6.103470,-2.906393,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.962329,1.060736,-4.285544,4.835473,2.418198,1.813805,-3.314817,0.169548,1.368828,8.896954,...,-1.584506,-2.591224,1.111903,-5.552404,-7.939174,7.069707,-1.482227,6.677629,2.730676,8
9996,1.321021,-5.286813,-2.082787,1.308841,0.463684,-0.024791,-1.762761,0.792561,-6.566239,6.633676,...,0.699120,-2.815310,-5.930531,-1.082705,-3.296279,7.150104,-1.324677,2.361122,0.209425,3
9997,-1.692802,3.934585,-0.876730,5.551027,2.005298,0.714866,-1.635832,-0.044646,5.998605,4.976243,...,2.148055,-0.845783,-2.192375,-7.951071,-2.233049,1.008963,0.003007,4.423275,-2.219654,5
9998,1.222638,1.887653,-0.107822,1.581197,0.065423,3.278822,-1.739180,0.154218,-0.315838,11.040958,...,-1.843708,-0.877138,-5.486035,-3.738888,-3.004359,3.760099,-0.026571,5.263076,-2.054908,1
9999,0.990962,2.608208,-1.894287,1.815938,4.252617,2.683276,-0.663357,-1.394372,-0.581244,4.080174,...,-2.659821,-4.377925,-1.458680,-1.665661,-1.288376,5.314838,-0.174741,0.357819,0.432436,7

In [3]:
ClassLabel="Class Label"
dataFeatures_true = true.drop(ClassLabel,axis = 1).values

r=len(dataFeatures_true)
dataFeatures_true=dataFeatures_true[:r]

In [4]:
dataPhenotypes_true = true[ClassLabel].values

In [5]:
iteration=len(dataFeatures_true[0])
sample_size=len(dataFeatures_true)

In [6]:
dataPhenotypes_true= dataPhenotypes_true[:r]

# Ruleset Dataframe

In [7]:
ruleset = pd.read_csv ('RulePopulationCifar10Vgg19100LCS2.csv')

ruleset

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,"-6.23939635,7.41998195","-3.2284351700000005,5.27973877","-7.231658825,7.544570225000001",#,#,#,#,#,#,#,...,0,1.850000e-08,0.168534,1,1462.323575,9994,0,0.40,376,2231
1,"-1.4927635999999995,6.601682799999999","-6.92314872,9.092237520000001",#,"-3.7731395599999997,3.1387668399999997",#,#,"-10.1023262,8.034826599999999",#,"-6.849005554999998,14.500950754999998",#,...,8,1.430000e-06,0.260417,1,1745.184990,9970,1,0.48,275,1056
2,#,"-5.525169185000001,8.738534185","-5.695446562499999,11.2257189625","-3.7209683799999995,3.19093802","-9.2552451,6.203788100000001",#,#,"-10.02296731,1.5688833100000004","-11.519511504999999,10.431852025",#,...,3,2.170000e-08,0.171233,1,1365.600187,9420,2,0.43,25,146
3,"-6.1787113,11.0219873","-5.699731775,6.061567495","-7.399247512500001,4.7553925125",#,#,"-4.290893083,7.912671883","-10.21845315,7.666794749999999",#,#,#,...,0,9.330000e-08,0.198145,1,1596.463805,9994,3,0.57,235,1186
4,#,"-8.941381836000001,9.075927684",#,"-1.25572704,9.34252944",#,#,#,#,#,"-1.2244510140000004,13.242865014",...,0,1.000000e+00,1.000000,1,1.000000,4,4,0.52,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17410,"-9.317782874999999,4.594546875",#,#,#,#,#,#,#,#,#,...,4,3.712100e-04,0.571429,1,1625.104000,9997,9997,0.35,0,0
17411,#,#,#,#,"-6.198884199999999,15.648305","-7.4062433709999995,7.159301910999999",#,#,#,#,...,2,8.470000e-07,0.307487,1,1435.422402,9998,9998,0.33,0,0
17412,#,"-4.880482945000001,12.386105345",#,"-5.06997342,7.141061219999999","0.8471030000000006,14.8517142",#,#,#,"-1.7101836873720533,13.59943984",#,...,2,8.470000e-07,0.307487,1,1164.920642,9998,9998,0.39,0,0
17413,#,#,#,#,"-15.7824527,4.236683000000001",#,#,#,#,#,...,9,1.000000e-01,1.000000,1,1005.464000,9999,9999,0.27,0,0
17414,#,"-6.426560870000001,12.09122947","-2.53459085,7.95176525",#,"-15.7824527,4.236683000000001",#,"-3.2602588999999997,7.823556699999999","-16.18142779,-5.24759136057603",#,#,...,9,1.000000e-01,1.000000,1,1335.000000,9999,9999,0.30,0,0

In [8]:
ruleset2=ruleset.replace("#",np.nan)

In [9]:
ruleset3=ruleset2.replace(np.nan,0)

In [10]:
ruleset3

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,"-6.23939635,7.41998195","-3.2284351700000005,5.27973877","-7.231658825,7.544570225000001",0,0,0,0,0,0,0,...,0,1.850000e-08,0.168534,1,1462.323575,9994,0,0.40,376,2231
1,"-1.4927635999999995,6.601682799999999","-6.92314872,9.092237520000001",0,"-3.7731395599999997,3.1387668399999997",0,0,"-10.1023262,8.034826599999999",0,"-6.849005554999998,14.500950754999998",0,...,8,1.430000e-06,0.260417,1,1745.184990,9970,1,0.48,275,1056
2,0,"-5.525169185000001,8.738534185","-5.695446562499999,11.2257189625","-3.7209683799999995,3.19093802","-9.2552451,6.203788100000001",0,0,"-10.02296731,1.5688833100000004","-11.519511504999999,10.431852025",0,...,3,2.170000e-08,0.171233,1,1365.600187,9420,2,0.43,25,146
3,"-6.1787113,11.0219873","-5.699731775,6.061567495","-7.399247512500001,4.7553925125",0,0,"-4.290893083,7.912671883","-10.21845315,7.666794749999999",0,0,0,...,0,9.330000e-08,0.198145,1,1596.463805,9994,3,0.57,235,1186
4,0,"-8.941381836000001,9.075927684",0,"-1.25572704,9.34252944",0,0,0,0,0,"-1.2244510140000004,13.242865014",...,0,1.000000e+00,1.000000,1,1.000000,4,4,0.52,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17410,"-9.317782874999999,4.594546875",0,0,0,0,0,0,0,0,0,...,4,3.712100e-04,0.571429,1,1625.104000,9997,9997,0.35,0,0
17411,0,0,0,0,"-6.198884199999999,15.648305","-7.4062433709999995,7.159301910999999",0,0,0,0,...,2,8.470000e-07,0.307487,1,1435.422402,9998,9998,0.33,0,0
17412,0,"-4.880482945000001,12.386105345",0,"-5.06997342,7.141061219999999","0.8471030000000006,14.8517142",0,0,0,"-1.7101836873720533,13.59943984",0,...,2,8.470000e-07,0.307487,1,1164.920642,9998,9998,0.39,0,0
17413,0,0,0,0,"-15.7824527,4.236683000000001",0,0,0,0,0,...,9,1.000000e-01,1.000000,1,1005.464000,9999,9999,0.27,0,0
17414,0,"-6.426560870000001,12.09122947","-2.53459085,7.95176525",0,"-15.7824527,4.236683000000001",0,"-3.2602588999999997,7.823556699999999","-16.18142779,-5.24759136057603",0,0,...,9,1.000000e-01,1.000000,1,1335.000000,9999,9999,0.30,0,0

In [11]:
Extra=['phenotype','Fitness','Accuracy','Numerosity','Avg Match Set Size','TimeStamp GA','Iteration Initialized','Specificity','Correct Count','Match Count']

In [12]:
correct=Extra[8]

In [13]:
#ruleset1
#Features = ruleset.drop(Extra,axis = 1).columns.values

#ruleset2
#Features = ruleset2.drop(Extra,axis = 1).columns.values

#ruleset3
Features = ruleset3.drop(Extra,axis = 1).columns.values
Feature_count=len(Features)

print(Feature_count)
Features

100

array(['N0', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'N11', 'N12', 'N13', 'N14', 'N15', 'N16', 'N17', 'N18', 'N19',
       'N20', 'N21', 'N22', 'N23', 'N24', 'N25', 'N26', 'N27', 'N28',
       'N29', 'N30', 'N31', 'N32', 'N33', 'N34', 'N35', 'N36', 'N37',
       'N38', 'N39', 'N40', 'N41', 'N42', 'N43', 'N44', 'N45', 'N46',
       'N47', 'N48', 'N49', 'N50', 'N51', 'N52', 'N53', 'N54', 'N55',
       'N56', 'N57', 'N58', 'N59', 'N60', 'N61', 'N62', 'N63', 'N64',
       'N65', 'N66', 'N67', 'N68', 'N69', 'N70', 'N71', 'N72', 'N73',
       'N74', 'N75', 'N76', 'N77', 'N78', 'N79', 'N80', 'N81', 'N82',
       'N83', 'N84', 'N85', 'N86', 'N87', 'N88', 'N89', 'N90', 'N91',
       'N92', 'N93', 'N94', 'N95', 'N96', 'N97', 'N98', 'N99'],
      dtype=object)

#New Ruleset

In [14]:
high="_high"
low="_low"

In [15]:
for x in range(0,Feature_count):

  feature_name=Features[x]

  if x==0:
    index_count_l=0
    index_count_h=1

  else:
    index_count_l=2*x
    index_count_h=index_count_l+1

  split_column=ruleset3[feature_name].str.split(',', expand=True)

  feature_name_low=feature_name+low
  feature_name_high=feature_name+high

  ruleset3.insert(index_count_l,feature_name_low,split_column[0])
  ruleset3.insert(index_count_h,feature_name_high,split_column[1])

  ruleset3=ruleset3.drop(columns=feature_name)

In [16]:
ruleset3=ruleset3.replace(np.nan,0)

In [17]:
ruleset3

,N0_low,N0_high,N1_low,N1_high,N2_low,N2_high,N3_low,N3_high,N4_low,N4_high,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,-6.23939635,7.41998195,-3.2284351700000005,5.27973877,-7.231658825,7.544570225000001,0,0,0,0,...,0,1.850000e-08,0.168534,1,1462.323575,9994,0,0.40,376,2231
1,-1.4927635999999995,6.601682799999999,-6.92314872,9.092237520000001,0,0,-3.7731395599999997,3.1387668399999997,0,0,...,8,1.430000e-06,0.260417,1,1745.184990,9970,1,0.48,275,1056
2,0,0,-5.525169185000001,8.738534185,-5.695446562499999,11.2257189625,-3.7209683799999995,3.19093802,-9.2552451,6.203788100000001,...,3,2.170000e-08,0.171233,1,1365.600187,9420,2,0.43,25,146
3,-6.1787113,11.0219873,-5.699731775,6.061567495,-7.399247512500001,4.7553925125,0,0,0,0,...,0,9.330000e-08,0.198145,1,1596.463805,9994,3,0.57,235,1186
4,0,0,-8.941381836000001,9.075927684,0,0,-1.25572704,9.34252944,0,0,...,0,1.000000e+00,1.000000,1,1.000000,4,4,0.52,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17410,-9.317782874999999,4.594546875,0,0,0,0,0,0,0,0,...,4,3.712100e-04,0.571429,1,1625.104000,9997,9997,0.35,0,0
17411,0,0,0,0,0,0,0,0,-6.198884199999999,15.648305,...,2,8.470000e-07,0.307487,1,1435.422402,9998,9998,0.33,0,0
17412,0,0,-4.880482945000001,12.386105345,0,0,-5.06997342,7.141061219999999,0.8471030000000006,14.8517142,...,2,8.470000e-07,0.307487,1,1164.920642,9998,9998,0.39,0,0
17413,0,0,0,0,0,0,0,0,-15.7824527,4.236683000000001,...,9,1.000000e-01,1.000000,1,1005.464000,9999,9999,0.27,0,0
17414,0,0,-6.426560870000001,12.09122947,-2.53459085,7.95176525,0,0,-15.7824527,4.236683000000001,...,9,1.000000e-01,1.000000,1,1335.000000,9999,9999,0.30,0,0

In [18]:
Features_1 = ruleset3.drop(Extra,axis = 1).columns.values
Features_1

array(['N0_low', 'N0_high', 'N1_low', 'N1_high', 'N2_low', 'N2_high',
       'N3_low', 'N3_high', 'N4_low', 'N4_high', 'N5_low', 'N5_high',
       'N6_low', 'N6_high', 'N7_low', 'N7_high', 'N8_low', 'N8_high',
       'N9_low', 'N9_high', 'N10_low', 'N10_high', 'N11_low', 'N11_high',
       'N12_low', 'N12_high', 'N13_low', 'N13_high', 'N14_low',
       'N14_high', 'N15_low', 'N15_high', 'N16_low', 'N16_high',
       'N17_low', 'N17_high', 'N18_low', 'N18_high', 'N19_low',
       'N19_high', 'N20_low', 'N20_high', 'N21_low', 'N21_high',
       'N22_low', 'N22_high', 'N23_low', 'N23_high', 'N24_low',
       'N24_high', 'N25_low', 'N25_high', 'N26_low', 'N26_high',
       'N27_low', 'N27_high', 'N28_low', 'N28_high', 'N29_low',
       'N29_high', 'N30_low', 'N30_high', 'N31_low', 'N31_high',
       'N32_low', 'N32_high', 'N33_low', 'N33_high', 'N34_low',
       'N34_high', 'N35_low', 'N35_high', 'N36_low', 'N36_high',
       'N37_low', 'N37_high', 'N38_low', 'N38_high', 'N39_low',
       'N39_high', 'N40_low', 'N40_high', 'N41_low', 'N41_high',
       'N42_low', 'N42_high', 'N43_low', 'N43_high', 'N44_low',
       'N44_high', 'N45_low', 'N45_high', 'N46_low', 'N46_high',
       'N47_low', 'N47_high', 'N48_low', 'N48_high', 'N49_low',
       'N49_high', 'N50_low', 'N50_high', 'N51_low', 'N51_high',
       'N52_low', 'N52_high', 'N53_low', 'N53_high', 'N54_low',
       'N54_high', 'N55_low', 'N55_high', 'N56_low', 'N56_high',
       'N57_low', 'N57_high', 'N58_low', 'N58_high', 'N59_low',
       'N59_high', 'N60_low', 'N60_high', 'N61_low', 'N61_high',
       'N62_low', 'N62_high', 'N63_low', 'N63_high', 'N64_low',
       'N64_high', 'N65_low', 'N65_high', 'N66_low', 'N66_high',
       'N67_low', 'N67_high', 'N68_low', 'N68_high', 'N69_low',
       'N69_high', 'N70_low', 'N70_high', 'N71_low', 'N71_high',
       'N72_low', 'N72_high', 'N73_low', 'N73_high', 'N74_low',
       'N74_high', 'N75_low', 'N75_high', 'N76_low', 'N76_high',
       'N77_low', 'N77_high', 'N78_low', 'N78_high', 'N79_low',
       'N79_high', 'N80_low', 'N80_high', 'N81_low', 'N81_high',
       'N82_low', 'N82_high', 'N83_low', 'N83_high', 'N84_low',
       'N84_high', 'N85_low', 'N85_high', 'N86_low', 'N86_high',
       'N87_low', 'N87_high', 'N88_low', 'N88_high', 'N89_low',
       'N89_high', 'N90_low', 'N90_high', 'N91_low', 'N91_high',
       'N92_low', 'N92_high', 'N93_low', 'N93_high', 'N94_low',
       'N94_high', 'N95_low', 'N95_high', 'N96_low', 'N96_high',
       'N97_low', 'N97_high', 'N98_low', 'N98_high', 'N99_low',
       'N99_high'], dtype=object)

#code

In [19]:
#number of classes
class_number=10

#enter first part of the file name here

#Google colab example: '/content/first part of file name_'
#first_part='/content/Vgg19_cifar10_100_shared_class_'

#non google colab:'first part of file name
first_part='Vgg19_cifar10_100_shared_class_'

#last part of file name
incorrect='_incorrect.csv'
instance_list=[]

In [20]:
for x in range(0,class_number):
  number=str(x)
  file=first_part+number+incorrect
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  instance_list.append(a)

In [21]:
dataFeatures_true[0]

array([-0.40689117,  2.5182478 ,  1.07885   ,  0.5424281 , -1.9916981 ,
        3.3936512 , -2.0006087 ,  1.4594278 ,  0.54412735,  8.005242  ,
       -1.0530542 ,  1.2614037 , -1.7158209 , -2.2308366 ,  1.391083  ,
       -1.1271632 ,  3.0722995 , -0.4180204 , -0.3543799 , -1.3581493 ,
       -6.1068687 ,  5.170712  ,  1.6370933 ,  0.98958063, -4.5793915 ,
        4.1515355 ,  2.9146566 , -4.0022497 , -9.51504   ,  6.559072  ,
       -6.9275856 , 10.398522  ,  2.4132924 , -0.64971393,  0.03355828,
        0.37710726,  2.3342068 ,  5.8542957 , -0.5764248 ,  1.199457  ,
       -1.7428559 , -1.1897433 ,  2.1025517 ,  0.6410002 , -3.9817355 ,
       -2.1496155 , -2.462383  ,  3.331544  , -2.5320315 ,  0.25360996,
       -6.2773504 , -0.8753843 ,  7.062905  , -4.9062266 ,  6.756814  ,
        2.347523  , -5.6317    , -2.5563889 , -1.4701462 ,  4.8650985 ,
       -1.7182645 ,  2.135411  , -3.6759725 , -5.3667207 , -3.896145  ,
       -6.127431  ,  1.8109941 ,  4.7982745 ,  4.3354855 , -0.6160006 ,
        2.929961  , -4.2835164 , -7.935171  , -0.23412676, -4.007546  ,
        3.366185  ,  0.380584  , -6.9412866 ,  4.9378486 , -0.9204375 ,
        2.8886468 , -0.01270127, -0.25118127, -1.4007264 , -4.0215015 ,
       -0.7105724 ,  1.1624525 ,  6.105257  , -5.287781  ,  7.63535   ,
       -6.11559   , -2.4560387 , -3.9189022 , -0.8546594 , -0.92062503,
       -6.2723985 , 12.150599  , -3.2117167 ,  4.2919936 , -1.8000226 ])

In [22]:
for feature in range(iteration):
  print(feature)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [23]:
incorrect_count_list=[]
ml='_LCS'

for x in range(0,class_number):

  incorrect_count=0

  #new class list
  b=instance_list[x]
  

  for y in b:

    #instance for class
    z=y[0]

    #filter ruleset by class
    class_check=dataPhenotypes_true[z-1]
    ruleset_filter= ruleset3[ruleset3['phenotype'] == class_check]
    
    #converts string to float
    ruleset_filter2=ruleset_filter.astype(float)


    #Checks feature for each rule in class
    for feature in range(iteration):
      f=dataFeatures_true[z-1][feature]

      #lowest range for feature
      l=2*feature

      #highest range for feature
      h=l+1

      #low feature name
      Low=Features_1[l]

      #high feature name
      High=Features_1[h]

      #when the count starts at 0
      if feature==0:
        ruleset_filter_test= ruleset_filter2[((ruleset_filter2[Low] < f)&(ruleset_filter2[High] >= f)) | (ruleset_filter2[High] == 0) ]
      
      #when the feature count is not 0
      else:
        ruleset_filter_test= ruleset_filter_test[((ruleset_filter_test[Low] < f)&(ruleset_filter_test[High] >= f)) | (ruleset_filter_test[High] == 0) ]
    
    #filters out all of the rows that have a correct count of zero
    ruleset_filter_test2= ruleset_filter_test[ruleset_filter_test[correct] != 0 ]

    #replaces 0 with #
    ruleset_filter_test3=ruleset_filter_test2.replace(0,'#')

    #adds
    if ruleset_filter_test3.empty:
      continue
    else:
      file_2='class_'+str(class_check)+'_iteration_'+str(z)+'_'+str(iteration)+ml+'.csv'
      ruleset_filter_test3.to_csv(file_2, index=False) 
      #files.download(file_2)
      incorrect_count+=1
    
  incorrect_count_list.append(incorrect_count)

In [24]:
incorrect_count_list

[268, 180, 360, 469, 359, 390, 228, 283, 193, 179]

In [25]:
correct_csv='_correct.csv'

In [26]:
mimic=[]

for x in range(0,class_number):
  number=str(x)
  file=first_part+number+correct_csv
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  b=len(a)
  total=b+incorrect_count_list[x]
  score=total/sample_size
  mimic.append(score)

In [27]:
mimic

[0.91, 0.9267, 0.9156, 0.9208, 0.901, 0.918, 0.9101, 0.9116, 0.8929, 0.8945]

In [28]:
average=sum(mimic)/class_number
average

0.91012