#Initialization

In [1]:
import pandas as pd
import numpy as np
#from google.colab import files

# Real Test Data

In [2]:
true = pd.read_csv ('TestingDataCifar10Vgg19Size50.csv')

true

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,Class Label
0,-1.409927,-1.247724,2.657260,-9.412471,-3.119530,2.423308,-9.237565,-0.086591,0.580297,3.088099,...,1.153778,-7.161221,-1.266568,-2.193147,2.304055,7.089179,-2.450800,-3.519078,4.773481,3
1,0.596765,0.248726,6.441457,1.530600,-0.280331,2.432632,-3.440261,-0.045972,6.262614,6.578016,...,1.108812,-9.055381,0.450545,-1.472301,3.214248,2.817699,-0.047939,2.834158,3.473419,8
2,0.555949,-0.335385,2.165705,0.440375,-2.181245,1.117639,-1.024648,0.207897,3.575315,3.764349,...,0.536972,-5.144194,-2.910773,-4.346794,5.757003,4.478575,1.053880,2.030664,1.732155,8
3,-0.393537,-1.510701,-1.766131,1.447005,2.307790,1.638390,1.674694,0.926802,2.281275,1.003283,...,-1.449271,-2.529675,1.312099,0.734500,1.088996,0.144995,1.321097,1.375216,2.214160,0
4,1.879739,-0.797323,0.712008,-3.072706,0.250941,-1.378701,4.734621,-2.097707,4.971477,1.203390,...,0.259970,-5.215339,2.576901,-0.067801,2.982326,7.052568,1.223448,2.074132,4.524567,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.443033,-6.778223,4.192811,-5.934762,-4.491750,2.172825,2.464512,1.134235,1.682799,4.676348,...,3.129048,-7.220518,1.736803,0.008010,-0.445414,6.196940,0.484516,2.817560,1.247734,8
9996,0.410364,-0.448138,4.638701,-2.926531,-7.946975,3.467588,-2.449722,-6.731284,2.932749,8.747683,...,0.414007,-5.915178,-0.127198,1.804613,4.268934,5.541410,-0.124404,-1.418162,-2.834198,3
9997,1.713879,-0.741180,6.216681,1.121108,0.374093,3.460661,-3.427820,0.743055,2.233798,0.117603,...,0.752315,-4.423781,-1.234255,-2.717735,4.038872,2.182154,-1.306942,-0.841053,-0.115771,5
9998,0.151390,-0.785029,4.750714,-3.040931,-3.386738,3.395213,-1.768147,-4.905481,6.986887,1.588388,...,3.216287,-7.356222,-0.145734,1.170851,3.225507,5.503082,-5.026220,1.135994,0.462717,1
9999,0.704306,-1.363593,4.193852,-1.506734,-3.758308,4.307255,-1.226341,-4.750979,2.191723,0.252612,...,1.790215,-3.049546,2.265989,0.093345,3.999055,4.593421,-3.623081,0.424016,3.464544,7

In [3]:
ClassLabel="Class Label"
dataFeatures_true = true.drop(ClassLabel,axis = 1).values

r=len(dataFeatures_true)
dataFeatures_true=dataFeatures_true[:r]

In [4]:
dataPhenotypes_true = true[ClassLabel].values

In [5]:
iteration=len(dataFeatures_true[0])
sample_size=len(dataFeatures_true)

In [6]:
dataPhenotypes_true= dataPhenotypes_true[:r]

# Ruleset Dataframe

In [7]:
ruleset = pd.read_csv ('RulePopulationCifar10Vgg1950LCS2.csv')

ruleset

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,#,"-5.6079594,3.507629400000001",#,"-8.28083425,5.681438050000001",#,"-10.149642414999999,8.763914815","-4.619698385000001,7.507911785000001",#,"-1.5656472799999994,16.280797279999998","-0.24982980000000055,10.6889178",...,3,1.048580e-04,0.400000,1,45.000000,272,0,0.56,2,5
1,"-12.156448155,2.871136155000001","-1.1641560000000006,5.925746400000001","-5.88691935,10.757293950000001",#,"-10.7528577,1.1282945","-4.500734145000001,9.617836745","-5.532291715,6.003727715000001","-9.245694550000001,2.199032150000001",#,"3.762193749999999,12.46347025",...,7,2.940000e-07,0.222222,1,76.631277,441,1,0.46,4,18
2,"-5.59402789,11.80633289",#,#,"-5.4523752000000005,6.665823400000001",#,"-4.714925035,5.674212035",#,#,"-3.4366531,13.8340997",#,...,4,7.610000e-06,0.307692,1,122.117995,464,2,0.50,28,91
3,#,#,#,#,#,"-9.108219106,9.006173734","-12.86243833,-1.6222142699999997","-8.703788320000001,10.11642892","7.081947540000001,16.86870746",#,...,1,1.000000e+00,1.000000,1,37.666667,422,3,0.46,3,3
4,#,#,#,#,"-3.9168909999999997,5.3562034","-5.225502025,6.761963825",#,#,#,#,...,6,1.150000e-05,0.320755,2,89.756710,472,4,0.50,17,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,"-3.4178845800000004,10.29149058","-9.3765243,0.7519077000000012",#,"-6.36985104,7.328982160000001","-11.2289766,2.101096600000001",#,#,"-5.682229820000001,2.9648970200000013","-4.51579708,7.573729879999999",#,...,3,1.930000e-07,0.268293,1,147.871181,495,495,0.48,0,0
489,#,#,"-4.20295284,9.62454744",#,#,#,#,#,#,#,...,2,4.610000e-10,0.146318,1,120.416499,496,496,0.34,0,0
490,"-3.7618027100000004,3.620168530000001",#,#,"-2.6495008442900225,4.19914055",#,"-4.043460495,6.761963825",#,"-11.09941876,7.212143960000001",#,#,...,2,4.610000e-10,0.146318,1,125.144755,496,496,0.40,0,0
491,#,"-10.434236400000001,3.9987792000000013","-5.81880421,6.472307149999999",#,#,#,#,"-10.340971410000002,4.155682410000001","2.4439147400000003,10.79144526",#,...,3,3.630000e-07,0.285714,1,87.968000,498,498,0.58,0,0
492,#,"-11.587625300000001,6.3903415",#,"-9.3319325,6.4744135","-11.407076700000001,4.531054300000001","-2.3077776749999996,7.015806875",#,#,"-8.04792358,11.23775038","-0.6939224500000001,8.50456985",...,6,0.000000e+00,0.000000,1,160.000000,498,498,0.36,0,1

In [8]:
ruleset2=ruleset.replace("#",np.nan)

In [9]:
ruleset3=ruleset2.replace(np.nan,0)

In [10]:
ruleset3

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,0,"-5.6079594,3.507629400000001",0,"-8.28083425,5.681438050000001",0,"-10.149642414999999,8.763914815","-4.619698385000001,7.507911785000001",0,"-1.5656472799999994,16.280797279999998","-0.24982980000000055,10.6889178",...,3,1.048580e-04,0.400000,1,45.000000,272,0,0.56,2,5
1,"-12.156448155,2.871136155000001","-1.1641560000000006,5.925746400000001","-5.88691935,10.757293950000001",0,"-10.7528577,1.1282945","-4.500734145000001,9.617836745","-5.532291715,6.003727715000001","-9.245694550000001,2.199032150000001",0,"3.762193749999999,12.46347025",...,7,2.940000e-07,0.222222,1,76.631277,441,1,0.46,4,18
2,"-5.59402789,11.80633289",0,0,"-5.4523752000000005,6.665823400000001",0,"-4.714925035,5.674212035",0,0,"-3.4366531,13.8340997",0,...,4,7.610000e-06,0.307692,1,122.117995,464,2,0.50,28,91
3,0,0,0,0,0,"-9.108219106,9.006173734","-12.86243833,-1.6222142699999997","-8.703788320000001,10.11642892","7.081947540000001,16.86870746",0,...,1,1.000000e+00,1.000000,1,37.666667,422,3,0.46,3,3
4,0,0,0,0,"-3.9168909999999997,5.3562034","-5.225502025,6.761963825",0,0,0,0,...,6,1.150000e-05,0.320755,2,89.756710,472,4,0.50,17,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,"-3.4178845800000004,10.29149058","-9.3765243,0.7519077000000012",0,"-6.36985104,7.328982160000001","-11.2289766,2.101096600000001",0,0,"-5.682229820000001,2.9648970200000013","-4.51579708,7.573729879999999",0,...,3,1.930000e-07,0.268293,1,147.871181,495,495,0.48,0,0
489,0,0,"-4.20295284,9.62454744",0,0,0,0,0,0,0,...,2,4.610000e-10,0.146318,1,120.416499,496,496,0.34,0,0
490,"-3.7618027100000004,3.620168530000001",0,0,"-2.6495008442900225,4.19914055",0,"-4.043460495,6.761963825",0,"-11.09941876,7.212143960000001",0,0,...,2,4.610000e-10,0.146318,1,125.144755,496,496,0.40,0,0
491,0,"-10.434236400000001,3.9987792000000013","-5.81880421,6.472307149999999",0,0,0,0,"-10.340971410000002,4.155682410000001","2.4439147400000003,10.79144526",0,...,3,3.630000e-07,0.285714,1,87.968000,498,498,0.58,0,0
492,0,"-11.587625300000001,6.3903415",0,"-9.3319325,6.4744135","-11.407076700000001,4.531054300000001","-2.3077776749999996,7.015806875",0,0,"-8.04792358,11.23775038","-0.6939224500000001,8.50456985",...,6,0.000000e+00,0.000000,1,160.000000,498,498,0.36,0,1

In [11]:
Extra=['phenotype','Fitness','Accuracy','Numerosity','Avg Match Set Size','TimeStamp GA','Iteration Initialized','Specificity','Correct Count','Match Count']

In [12]:
correct=Extra[8]

In [13]:
#ruleset1
#Features = ruleset.drop(Extra,axis = 1).columns.values

#ruleset2
#Features = ruleset2.drop(Extra,axis = 1).columns.values

#ruleset3
Features = ruleset3.drop(Extra,axis = 1).columns.values
Feature_count=len(Features)

print(Feature_count)
Features

50

array(['N0', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'N11', 'N12', 'N13', 'N14', 'N15', 'N16', 'N17', 'N18', 'N19',
       'N20', 'N21', 'N22', 'N23', 'N24', 'N25', 'N26', 'N27', 'N28',
       'N29', 'N30', 'N31', 'N32', 'N33', 'N34', 'N35', 'N36', 'N37',
       'N38', 'N39', 'N40', 'N41', 'N42', 'N43', 'N44', 'N45', 'N46',
       'N47', 'N48', 'N49'], dtype=object)

#New Ruleset

In [14]:
high="_high"
low="_low"

In [15]:
for x in range(0,Feature_count):

  feature_name=Features[x]

  if x==0:
    index_count_l=0
    index_count_h=1

  else:
    index_count_l=2*x
    index_count_h=index_count_l+1

  split_column=ruleset3[feature_name].str.split(',', expand=True)

  feature_name_low=feature_name+low
  feature_name_high=feature_name+high

  ruleset3.insert(index_count_l,feature_name_low,split_column[0])
  ruleset3.insert(index_count_h,feature_name_high,split_column[1])

  ruleset3=ruleset3.drop(columns=feature_name)

In [16]:
ruleset3=ruleset3.replace(np.nan,0)

In [17]:
ruleset3

,N0_low,N0_high,N1_low,N1_high,N2_low,N2_high,N3_low,N3_high,N4_low,N4_high,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,0,0,-5.6079594,3.507629400000001,0,0,-8.28083425,5.681438050000001,0,0,...,3,1.048580e-04,0.400000,1,45.000000,272,0,0.56,2,5
1,-12.156448155,2.871136155000001,-1.1641560000000006,5.925746400000001,-5.88691935,10.757293950000001,0,0,-10.7528577,1.1282945,...,7,2.940000e-07,0.222222,1,76.631277,441,1,0.46,4,18
2,-5.59402789,11.80633289,0,0,0,0,-5.4523752000000005,6.665823400000001,0,0,...,4,7.610000e-06,0.307692,1,122.117995,464,2,0.50,28,91
3,0,0,0,0,0,0,0,0,0,0,...,1,1.000000e+00,1.000000,1,37.666667,422,3,0.46,3,3
4,0,0,0,0,0,0,0,0,-3.9168909999999997,5.3562034,...,6,1.150000e-05,0.320755,2,89.756710,472,4,0.50,17,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,-3.4178845800000004,10.29149058,-9.3765243,0.7519077000000012,0,0,-6.36985104,7.328982160000001,-11.2289766,2.101096600000001,...,3,1.930000e-07,0.268293,1,147.871181,495,495,0.48,0,0
489,0,0,0,0,-4.20295284,9.62454744,0,0,0,0,...,2,4.610000e-10,0.146318,1,120.416499,496,496,0.34,0,0
490,-3.7618027100000004,3.620168530000001,0,0,0,0,-2.6495008442900225,4.19914055,0,0,...,2,4.610000e-10,0.146318,1,125.144755,496,496,0.40,0,0
491,0,0,-10.434236400000001,3.9987792000000013,-5.81880421,6.472307149999999,0,0,0,0,...,3,3.630000e-07,0.285714,1,87.968000,498,498,0.58,0,0
492,0,0,-11.587625300000001,6.3903415,0,0,-9.3319325,6.4744135,-11.407076700000001,4.531054300000001,...,6,0.000000e+00,0.000000,1,160.000000,498,498,0.36,0,1

In [18]:
Features_1 = ruleset3.drop(Extra,axis = 1).columns.values
Features_1

array(['N0_low', 'N0_high', 'N1_low', 'N1_high', 'N2_low', 'N2_high',
       'N3_low', 'N3_high', 'N4_low', 'N4_high', 'N5_low', 'N5_high',
       'N6_low', 'N6_high', 'N7_low', 'N7_high', 'N8_low', 'N8_high',
       'N9_low', 'N9_high', 'N10_low', 'N10_high', 'N11_low', 'N11_high',
       'N12_low', 'N12_high', 'N13_low', 'N13_high', 'N14_low',
       'N14_high', 'N15_low', 'N15_high', 'N16_low', 'N16_high',
       'N17_low', 'N17_high', 'N18_low', 'N18_high', 'N19_low',
       'N19_high', 'N20_low', 'N20_high', 'N21_low', 'N21_high',
       'N22_low', 'N22_high', 'N23_low', 'N23_high', 'N24_low',
       'N24_high', 'N25_low', 'N25_high', 'N26_low', 'N26_high',
       'N27_low', 'N27_high', 'N28_low', 'N28_high', 'N29_low',
       'N29_high', 'N30_low', 'N30_high', 'N31_low', 'N31_high',
       'N32_low', 'N32_high', 'N33_low', 'N33_high', 'N34_low',
       'N34_high', 'N35_low', 'N35_high', 'N36_low', 'N36_high',
       'N37_low', 'N37_high', 'N38_low', 'N38_high', 'N39_low',
       'N39_high', 'N40_low', 'N40_high', 'N41_low', 'N41_high',
       'N42_low', 'N42_high', 'N43_low', 'N43_high', 'N44_low',
       'N44_high', 'N45_low', 'N45_high', 'N46_low', 'N46_high',
       'N47_low', 'N47_high', 'N48_low', 'N48_high', 'N49_low',
       'N49_high'], dtype=object)

#code

In [19]:
#number of classes
class_number=10

#enter first part of the file name here

#Google colab example: '/content/first part of file name_'
#first_part='/content/Vgg19_cifar10_50_shared_class_'

#non google colab:'first part of file name
first_part='Vgg19_cifar10_50_shared_class_'

#last part of file name
incorrect='_incorrect.csv'
instance_list=[]

In [20]:
for x in range(0,class_number):
  number=str(x)
  file=first_part+number+incorrect
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  instance_list.append(a)

In [21]:
dataFeatures_true[0]

array([-1.409927  , -1.2477244 ,  2.65726   , -9.412471  , -3.1195304 ,
        2.4233081 , -9.237565  , -0.08659078,  0.5802972 ,  3.0880985 ,
        2.3223865 , -4.0432277 ,  3.490866  , -5.290625  , -0.83139986,
        1.6579767 , -0.65736043,  3.3160028 ,  6.0966225 ,  9.603663  ,
        4.7706866 , -3.44926   ,  2.1602101 , -0.66697943,  1.09006   ,
        1.7484442 , -7.342855  ,  0.09730432,  1.5335996 , -2.7736912 ,
       -2.0363789 , -2.0485554 ,  1.7055231 , -1.8418118 ,  9.942271  ,
       -0.59438694,  1.9283111 , -5.1948633 ,  0.9065664 , -0.90830064,
        1.2538987 ,  1.1537778 , -7.1612215 , -1.2665682 , -2.1931472 ,
        2.3040552 ,  7.0891786 , -2.4507995 , -3.5190778 ,  4.773481  ])

In [22]:
for feature in range(iteration):
  print(feature)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [23]:
incorrect_count_list=[]
ml='_LCS'

for x in range(0,class_number):

  incorrect_count=0

  #new class list
  b=instance_list[x]
  

  for y in b:

    #instance for class
    z=y[0]

    #filter ruleset by class
    class_check=dataPhenotypes_true[z-1]
    ruleset_filter= ruleset3[ruleset3['phenotype'] == class_check]
    
    #converts string to float
    ruleset_filter2=ruleset_filter.astype(float)


    #Checks feature for each rule in class
    for feature in range(iteration):
      f=dataFeatures_true[z-1][feature]

      #lowest range for feature
      l=2*feature

      #highest range for feature
      h=l+1

      #low feature name
      Low=Features_1[l]

      #high feature name
      High=Features_1[h]

      #when the count starts at 0
      if feature==0:
        ruleset_filter_test= ruleset_filter2[((ruleset_filter2[Low] < f)&(ruleset_filter2[High] >= f)) | (ruleset_filter2[High] == 0) ]
      
      #when the feature count is not 0
      else:
        ruleset_filter_test= ruleset_filter_test[((ruleset_filter_test[Low] < f)&(ruleset_filter_test[High] >= f)) | (ruleset_filter_test[High] == 0) ]
    
    #filters out all of the rows that have a correct count of zero
    ruleset_filter_test2= ruleset_filter_test[ruleset_filter_test[correct] != 0 ]

    #replaces 0 with #
    ruleset_filter_test3=ruleset_filter_test2.replace(0,'#')

    #adds
    if ruleset_filter_test3.empty:
      continue
    else:
      file_2=str(iteration)+'_class_'+str(class_check)+'_iteration_'+str(z)+'_'+ml+'.csv'
      ruleset_filter_test3.to_csv(file_2, index=False) 
      #files.download(file_2)
      incorrect_count+=1
    
  incorrect_count_list.append(incorrect_count)

In [24]:
incorrect_count_list

[308, 210, 507, 602, 413, 427, 329, 315, 326, 224]

In [25]:
correct_csv='_correct.csv'

In [26]:
mimic=[]

for x in range(0,class_number):
  number=str(x)
  file=first_part+number+correct_csv
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  b=len(a)
  total=b+incorrect_count_list[x]
  score=total/sample_size
  mimic.append(score)

In [27]:
mimic

[0.7458, 0.8063, 0.9258, 0.9209, 0.8217, 0.911, 0.8873, 0.9054, 0.9132, 0.8715]

In [28]:
average=sum(mimic)/class_number
average

0.8708899999999999