#Initialization

In [1]:
import pandas as pd
import numpy as np
#from google.colab import files

# Real Test Data

In [2]:
#true = pd.read_csv ('/content/TestingDataFashionMnistResnetSize100.csv')
true = pd.read_csv ('TestingDataFashionMnistResnetSize100.csv')

true

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Class Label
0,-0.716927,0.749618,-0.870767,-0.066707,0.058773,0.618856,0.391601,-0.717372,-0.755384,-1.366520,...,-1.699086,0.408796,-0.114875,-0.384992,-0.048404,-0.659013,0.647546,-0.074845,0.446118,9
1,-0.139435,-0.700259,-0.347272,0.007387,-0.768767,-0.503844,0.588896,0.721979,-0.629829,-1.883061,...,-1.695145,0.537973,-0.538199,-0.258903,0.162012,0.776664,-1.131113,0.143311,-0.701194,2
2,-0.281551,0.872183,0.371841,-0.415458,-0.603759,-0.020521,0.382745,0.491034,-0.185932,-0.797253,...,-0.595935,-0.103619,-1.457614,0.242761,0.783973,-1.200808,-0.201946,0.394235,-1.315444,1
3,-0.390214,2.210951,0.410171,-0.677084,1.145737,0.280417,0.906006,-0.346769,-0.215967,-1.274862,...,-1.006640,-0.402353,-0.733550,0.616438,0.471879,-0.025359,-1.476012,0.332266,-1.708209,1
4,-0.198602,-0.968852,0.356614,-0.875770,-0.084753,0.192117,0.559864,0.283957,-0.214270,-1.248679,...,-1.221779,-0.251775,-1.116550,0.277458,0.451630,0.624320,-1.238743,1.156032,-0.255379,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.397274,0.160435,-0.875297,0.437970,-0.464453,1.319541,0.422359,0.075925,-1.037880,-2.243120,...,-1.409385,0.268110,-1.028856,-0.039770,1.057297,-0.338686,0.274451,-0.234332,0.312138,9
9996,-0.622075,0.666807,0.378065,0.156215,0.641731,0.424205,-0.478770,-0.066350,-0.446386,-1.635451,...,-0.672303,0.298350,-0.095811,0.425188,-0.120787,-0.461846,-1.176381,0.201971,-1.258323,1
9997,0.013692,0.472063,0.500845,-1.087434,0.825062,0.979721,-0.021014,-0.557651,-0.891606,-2.292054,...,-2.410235,0.483820,-0.235535,-0.298020,0.577883,-0.255010,-0.288780,1.984122,-0.401339,8
9998,-0.379348,-0.141647,-0.257887,0.013843,0.620086,0.467275,1.098542,-0.163796,0.068679,-1.066082,...,-0.722286,-0.456653,-0.063292,0.350411,0.299885,-1.335027,-1.094977,0.901470,-1.256962,1
9999,0.254054,0.687115,-0.965656,-1.178409,-0.423984,0.413217,-0.256355,0.838349,-0.172921,-1.730810,...,-0.230462,-1.240064,0.024389,-0.552865,0.702033,0.291455,0.092808,-0.047166,-0.273389,5

In [3]:
ClassLabel="Class Label"
dataFeatures_true = true.drop(ClassLabel,axis = 1).values

r=len(dataFeatures_true)
dataFeatures_true=dataFeatures_true[:r]

In [4]:
dataPhenotypes_true = true[ClassLabel].values

In [5]:
iteration=len(dataFeatures_true[0])
sample_size=len(dataFeatures_true)

In [6]:
dataPhenotypes_true= dataPhenotypes_true[:r]

# Ruleset Dataframe

In [7]:
#ruleset = pd.read_csv ('/content/RulePopulationFashionMnistResnet100LCS2.csv')
ruleset = pd.read_csv ('RulePopulationFashionMnistResnet100LCS2.csv')

ruleset

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,"-2.544457777,0.26288217699999983",#,"-1.3317360125,0.07162281250000013","-0.20573294999999991,1.88159835",#,#,"-1.831862912,2.017444072",#,"-1.131616678,1.133171518",#,...,5,1.000000,1.000000,1,1.000000,0,0,0.52,1,1
1,#,#,"-1.645775138,2.395898278","-1.13033182,1.42085088","-0.7237751450000001,0.475708305","-0.9380202374999999,2.4007110375","-0.61462127,1.52388261","-2.62432526,-0.1470025399999999",#,"-2.957178204,-0.143358396",...,3,0.000105,0.400000,1,175.600000,9105,1,0.53,2,5
2,"-2.726450655,0.661718255",#,#,"-2.45829905,0.5567350499999999",#,#,"-1.039500601,1.419778861",#,#,#,...,1,0.000105,0.400000,1,42.000000,4696,2,0.38,2,5
3,#,#,"-1.4845826375000004,2.7254938375000006","-1.50373386,-0.11217966000000013",#,"0.1354337280000001,1.5599590719999998",#,"-0.2970357250000002,1.715788985",#,"-2.425979389,0.09473418899999975",...,5,0.000126,0.407407,1,403.224185,9992,3,0.46,22,54
4,"-1.5550767085000001,1.4942753105","-1.2265288719999998,2.020018072","-1.6003169625000004,2.0484159825000003",#,#,"-0.621114291,1.426640891",#,"-1.4064629499999999,1.58696867","-0.9866621435,1.7413781835",#,...,1,0.161506,0.833333,1,200.766374,9299,4,0.50,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17626,"-3.079289335810633,0.7169468184999999","-0.532316112,1.7260661400000001",#,#,"-1.9016108589999998,1.504922139",#,#,#,#,"-2.7428787029999997,0.8330173029999999",...,7,0.000773,0.614846,1,293.701055,9997,9997,0.36,0,0
17627,#,"0.24682466000000003,1.56299234","-1.7272654410000003,1.3039896210000002","-1.518185334,1.404078486","-1.576869436,0.534221436",#,#,#,"-1.319451051,1.3571168169999999",#,...,8,0.000311,0.510084,1,257.543177,9998,9998,0.38,0,0
17628,"-1.160225527,0.679066167","0.24682466000000003,1.56299234",#,#,#,#,#,#,#,#,...,8,0.000311,0.510084,1,293.046966,9998,9998,0.40,0,0
17629,"-0.60262786,1.139801497830041","-1.5265896840000002,0.7986398840000001",#,"-3.377778552140726,1.592898831",#,"-1.7675282495,0.36140458249999996","-1.0664299980000003,2.569026598",#,"-1.205243584,1.16248953",#,...,2,0.100000,1.000000,1,566.000000,9999,9999,0.37,0,0
17630,#,#,"-3.0878688195000006,1.6748900310000003",#,#,#,#,"-0.3750530500000002,1.6893825500000001",#,#,...,2,0.100000,1.000000,1,428.500000,9999,9999,0.34,0,0

In [8]:
ruleset2=ruleset.replace("#",np.nan)

In [9]:
ruleset3=ruleset2.replace(np.nan,0)

In [10]:
ruleset3

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,"-2.544457777,0.26288217699999983",0,"-1.3317360125,0.07162281250000013","-0.20573294999999991,1.88159835",0,0,"-1.831862912,2.017444072",0,"-1.131616678,1.133171518",0,...,5,1.000000,1.000000,1,1.000000,0,0,0.52,1,1
1,0,0,"-1.645775138,2.395898278","-1.13033182,1.42085088","-0.7237751450000001,0.475708305","-0.9380202374999999,2.4007110375","-0.61462127,1.52388261","-2.62432526,-0.1470025399999999",0,"-2.957178204,-0.143358396",...,3,0.000105,0.400000,1,175.600000,9105,1,0.53,2,5
2,"-2.726450655,0.661718255",0,0,"-2.45829905,0.5567350499999999",0,0,"-1.039500601,1.419778861",0,0,0,...,1,0.000105,0.400000,1,42.000000,4696,2,0.38,2,5
3,0,0,"-1.4845826375000004,2.7254938375000006","-1.50373386,-0.11217966000000013",0,"0.1354337280000001,1.5599590719999998",0,"-0.2970357250000002,1.715788985",0,"-2.425979389,0.09473418899999975",...,5,0.000126,0.407407,1,403.224185,9992,3,0.46,22,54
4,"-1.5550767085000001,1.4942753105","-1.2265288719999998,2.020018072","-1.6003169625000004,2.0484159825000003",0,0,"-0.621114291,1.426640891",0,"-1.4064629499999999,1.58696867","-0.9866621435,1.7413781835",0,...,1,0.161506,0.833333,1,200.766374,9299,4,0.50,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17626,"-3.079289335810633,0.7169468184999999","-0.532316112,1.7260661400000001",0,0,"-1.9016108589999998,1.504922139",0,0,0,0,"-2.7428787029999997,0.8330173029999999",...,7,0.000773,0.614846,1,293.701055,9997,9997,0.36,0,0
17627,0,"0.24682466000000003,1.56299234","-1.7272654410000003,1.3039896210000002","-1.518185334,1.404078486","-1.576869436,0.534221436",0,0,0,"-1.319451051,1.3571168169999999",0,...,8,0.000311,0.510084,1,257.543177,9998,9998,0.38,0,0
17628,"-1.160225527,0.679066167","0.24682466000000003,1.56299234",0,0,0,0,0,0,0,0,...,8,0.000311,0.510084,1,293.046966,9998,9998,0.40,0,0
17629,"-0.60262786,1.139801497830041","-1.5265896840000002,0.7986398840000001",0,"-3.377778552140726,1.592898831",0,"-1.7675282495,0.36140458249999996","-1.0664299980000003,2.569026598",0,"-1.205243584,1.16248953",0,...,2,0.100000,1.000000,1,566.000000,9999,9999,0.37,0,0
17630,0,0,"-3.0878688195000006,1.6748900310000003",0,0,0,0,"-0.3750530500000002,1.6893825500000001",0,0,...,2,0.100000,1.000000,1,428.500000,9999,9999,0.34,0,0

In [11]:
Extra=['phenotype','Fitness','Accuracy','Numerosity','Avg Match Set Size','TimeStamp GA','Iteration Initialized','Specificity','Correct Count','Match Count']

In [12]:
correct=Extra[8]

In [13]:
#ruleset1
#Features = ruleset.drop(Extra,axis = 1).columns.values

#ruleset2
#Features = ruleset2.drop(Extra,axis = 1).columns.values

#ruleset3
Features = ruleset3.drop(Extra,axis = 1).columns.values
Feature_count=len(Features)

print(Feature_count)
Features

100

array(['N0', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'N11', 'N12', 'N13', 'N14', 'N15', 'N16', 'N17', 'N18', 'N19',
       'N20', 'N21', 'N22', 'N23', 'N24', 'N25', 'N26', 'N27', 'N28',
       'N29', 'N30', 'N31', 'N32', 'N33', 'N34', 'N35', 'N36', 'N37',
       'N38', 'N39', 'N40', 'N41', 'N42', 'N43', 'N44', 'N45', 'N46',
       'N47', 'N48', 'N49', 'N50', 'N51', 'N52', 'N53', 'N54', 'N55',
       'N56', 'N57', 'N58', 'N59', 'N60', 'N61', 'N62', 'N63', 'N64',
       'N65', 'N66', 'N67', 'N68', 'N69', 'N70', 'N71', 'N72', 'N73',
       'N74', 'N75', 'N76', 'N77', 'N78', 'N79', 'N80', 'N81', 'N82',
       'N83', 'N84', 'N85', 'N86', 'N87', 'N88', 'N89', 'N90', 'N91',
       'N92', 'N93', 'N94', 'N95', 'N96', 'N97', 'N98', 'N99'],
      dtype=object)

#New Ruleset

In [14]:
high="_high"
low="_low"

In [15]:
for x in range(0,Feature_count):

  feature_name=Features[x]

  if x==0:
    index_count_l=0
    index_count_h=1

  else:
    index_count_l=2*x
    index_count_h=index_count_l+1

  split_column=ruleset3[feature_name].str.split(',', expand=True)

  feature_name_low=feature_name+low
  feature_name_high=feature_name+high

  ruleset3.insert(index_count_l,feature_name_low,split_column[0])
  ruleset3.insert(index_count_h,feature_name_high,split_column[1])

  ruleset3=ruleset3.drop(columns=feature_name)

In [16]:
ruleset3=ruleset3.replace(np.nan,0)

In [17]:
ruleset3

,N0_low,N0_high,N1_low,N1_high,N2_low,N2_high,N3_low,N3_high,N4_low,N4_high,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,-2.544457777,0.26288217699999983,0,0,-1.3317360125,0.07162281250000013,-0.20573294999999991,1.88159835,0,0,...,5,1.000000,1.000000,1,1.000000,0,0,0.52,1,1
1,0,0,0,0,-1.645775138,2.395898278,-1.13033182,1.42085088,-0.7237751450000001,0.475708305,...,3,0.000105,0.400000,1,175.600000,9105,1,0.53,2,5
2,-2.726450655,0.661718255,0,0,0,0,-2.45829905,0.5567350499999999,0,0,...,1,0.000105,0.400000,1,42.000000,4696,2,0.38,2,5
3,0,0,0,0,-1.4845826375000004,2.7254938375000006,-1.50373386,-0.11217966000000013,0,0,...,5,0.000126,0.407407,1,403.224185,9992,3,0.46,22,54
4,-1.5550767085000001,1.4942753105,-1.2265288719999998,2.020018072,-1.6003169625000004,2.0484159825000003,0,0,0,0,...,1,0.161506,0.833333,1,200.766374,9299,4,0.50,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17626,-3.079289335810633,0.7169468184999999,-0.532316112,1.7260661400000001,0,0,0,0,-1.9016108589999998,1.504922139,...,7,0.000773,0.614846,1,293.701055,9997,9997,0.36,0,0
17627,0,0,0.24682466000000003,1.56299234,-1.7272654410000003,1.3039896210000002,-1.518185334,1.404078486,-1.576869436,0.534221436,...,8,0.000311,0.510084,1,257.543177,9998,9998,0.38,0,0
17628,-1.160225527,0.679066167,0.24682466000000003,1.56299234,0,0,0,0,0,0,...,8,0.000311,0.510084,1,293.046966,9998,9998,0.40,0,0
17629,-0.60262786,1.139801497830041,-1.5265896840000002,0.7986398840000001,0,0,-3.377778552140726,1.592898831,0,0,...,2,0.100000,1.000000,1,566.000000,9999,9999,0.37,0,0
17630,0,0,0,0,-3.0878688195000006,1.6748900310000003,0,0,0,0,...,2,0.100000,1.000000,1,428.500000,9999,9999,0.34,0,0

In [18]:
Features_1 = ruleset3.drop(Extra,axis = 1).columns.values
Features_1

array(['N0_low', 'N0_high', 'N1_low', 'N1_high', 'N2_low', 'N2_high',
       'N3_low', 'N3_high', 'N4_low', 'N4_high', 'N5_low', 'N5_high',
       'N6_low', 'N6_high', 'N7_low', 'N7_high', 'N8_low', 'N8_high',
       'N9_low', 'N9_high', 'N10_low', 'N10_high', 'N11_low', 'N11_high',
       'N12_low', 'N12_high', 'N13_low', 'N13_high', 'N14_low',
       'N14_high', 'N15_low', 'N15_high', 'N16_low', 'N16_high',
       'N17_low', 'N17_high', 'N18_low', 'N18_high', 'N19_low',
       'N19_high', 'N20_low', 'N20_high', 'N21_low', 'N21_high',
       'N22_low', 'N22_high', 'N23_low', 'N23_high', 'N24_low',
       'N24_high', 'N25_low', 'N25_high', 'N26_low', 'N26_high',
       'N27_low', 'N27_high', 'N28_low', 'N28_high', 'N29_low',
       'N29_high', 'N30_low', 'N30_high', 'N31_low', 'N31_high',
       'N32_low', 'N32_high', 'N33_low', 'N33_high', 'N34_low',
       'N34_high', 'N35_low', 'N35_high', 'N36_low', 'N36_high',
       'N37_low', 'N37_high', 'N38_low', 'N38_high', 'N39_low',
       'N39_high', 'N40_low', 'N40_high', 'N41_low', 'N41_high',
       'N42_low', 'N42_high', 'N43_low', 'N43_high', 'N44_low',
       'N44_high', 'N45_low', 'N45_high', 'N46_low', 'N46_high',
       'N47_low', 'N47_high', 'N48_low', 'N48_high', 'N49_low',
       'N49_high', 'N50_low', 'N50_high', 'N51_low', 'N51_high',
       'N52_low', 'N52_high', 'N53_low', 'N53_high', 'N54_low',
       'N54_high', 'N55_low', 'N55_high', 'N56_low', 'N56_high',
       'N57_low', 'N57_high', 'N58_low', 'N58_high', 'N59_low',
       'N59_high', 'N60_low', 'N60_high', 'N61_low', 'N61_high',
       'N62_low', 'N62_high', 'N63_low', 'N63_high', 'N64_low',
       'N64_high', 'N65_low', 'N65_high', 'N66_low', 'N66_high',
       'N67_low', 'N67_high', 'N68_low', 'N68_high', 'N69_low',
       'N69_high', 'N70_low', 'N70_high', 'N71_low', 'N71_high',
       'N72_low', 'N72_high', 'N73_low', 'N73_high', 'N74_low',
       'N74_high', 'N75_low', 'N75_high', 'N76_low', 'N76_high',
       'N77_low', 'N77_high', 'N78_low', 'N78_high', 'N79_low',
       'N79_high', 'N80_low', 'N80_high', 'N81_low', 'N81_high',
       'N82_low', 'N82_high', 'N83_low', 'N83_high', 'N84_low',
       'N84_high', 'N85_low', 'N85_high', 'N86_low', 'N86_high',
       'N87_low', 'N87_high', 'N88_low', 'N88_high', 'N89_low',
       'N89_high', 'N90_low', 'N90_high', 'N91_low', 'N91_high',
       'N92_low', 'N92_high', 'N93_low', 'N93_high', 'N94_low',
       'N94_high', 'N95_low', 'N95_high', 'N96_low', 'N96_high',
       'N97_low', 'N97_high', 'N98_low', 'N98_high', 'N99_low',
       'N99_high'], dtype=object)

#code

In [19]:
#number of classes
class_number=10

#enter first part of the file name here

#Google colab example: '/content/first part of file name_'
#first_part='/content/Resnet_fashion_mnist_100_shared_class_'

#non google colab:'first part of file name
first_part='Resnet_fashion_mnist_100_shared_class_'

#last part of file name
incorrect='_incorrect.csv'
instance_list=[]

In [20]:
for x in range(0,class_number):
  number=str(x)
  file=first_part+number+incorrect
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  instance_list.append(a)

In [21]:
dataFeatures_true[0]

array([-0.71692693,  0.749618  , -0.87076694, -0.06670667,  0.05877322,
        0.61885566,  0.39160118, -0.717372  , -0.755384  , -1.3665199 ,
        1.1081152 ,  0.04901048,  0.11854061, -1.4481974 ,  0.10794421,
       -0.28238994,  0.23379971,  1.1621513 , -0.07979105,  1.2373265 ,
       -0.9656034 ,  0.5346321 , -0.8900931 , -0.18303509, -1.0626253 ,
       -0.09813647, -0.27199408,  0.2880838 , -0.87376404, -1.1053318 ,
        0.42715517,  0.40292436,  0.48993203, -1.1893594 , -0.33626327,
        0.476553  , -0.55146945,  0.20673552, -0.16455837,  0.8091359 ,
        1.9775457 , -1.4720365 ,  1.0185206 , -1.3243672 ,  0.7367432 ,
       -1.1649424 , -0.35076514, -0.74405134, -0.45575744, -1.325752  ,
       -0.379944  ,  0.49000922,  0.11545987, -0.44575202, -0.86736   ,
       -1.1036435 , -0.4278932 ,  0.8815955 ,  1.1424367 , -0.56512827,
        0.45076162, -0.17676355, -0.40648448, -0.17393151,  2.0751834 ,
        1.3689629 , -0.83732766,  0.39042872, -0.516253  , -0.3513048 ,
        1.0693537 ,  0.59852713,  0.7995065 , -1.139788  ,  0.10418089,
       -0.6473784 ,  0.06280608, -0.26385438,  0.6844246 ,  0.07852753,
        0.9175304 , -0.00261537,  0.950377  , -1.105308  , -1.4665372 ,
       -0.03428839,  0.2888118 ,  0.6836923 , -0.6638345 , -0.08987638,
       -0.76316285, -1.6990861 ,  0.40879634, -0.11487501, -0.38499153,
       -0.04840399, -0.6590132 ,  0.6475461 , -0.07484468,  0.44611818])

In [22]:
for feature in range(iteration):
  print(feature)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [23]:
incorrect_count_list=[]
ml='_LCS'

for x in range(0,class_number):

  incorrect_count=0

  #new class list
  b=instance_list[x]
  

  for y in b:

    #instance for class
    z=y[0]

    #filter ruleset by class
    class_check=dataPhenotypes_true[z-1]
    ruleset_filter= ruleset3[ruleset3['phenotype'] == class_check]
    
    #converts string to float
    ruleset_filter2=ruleset_filter.astype(float)


    #Checks feature for each rule in class
    for feature in range(iteration):
      f=dataFeatures_true[z-1][feature]

      #lowest range for feature
      l=2*feature

      #highest range for feature
      h=l+1

      #low feature name
      Low=Features_1[l]

      #high feature name
      High=Features_1[h]

      #when the count starts at 0
      if feature==0:
        ruleset_filter_test= ruleset_filter2[((ruleset_filter2[Low] < f)&(ruleset_filter2[High] >= f)) | (ruleset_filter2[High] == 0) ]
      
      #when the feature count is not 0
      else:
        ruleset_filter_test= ruleset_filter_test[((ruleset_filter_test[Low] < f)&(ruleset_filter_test[High] >= f)) | (ruleset_filter_test[High] == 0) ]
    
    #filters out all of the rows that have a correct count of zero
    ruleset_filter_test2= ruleset_filter_test[ruleset_filter_test[correct] != 0 ]

    #replaces 0 with #
    ruleset_filter_test3=ruleset_filter_test2.replace(0,'#')

    #adds
    if ruleset_filter_test3.empty:
      continue
    else:
      file_2=str(iteration)+'_class_'+str(class_check)+'_iteration_'+str(z)+'_'+ml+'.csv'
      ruleset_filter_test3.to_csv(file_2, index=False) 
      #files.download(file_2)
      incorrect_count+=1
    
  incorrect_count_list.append(incorrect_count)

In [24]:
incorrect_count_list

[363, 50, 399, 287, 459, 154, 632, 157, 143, 141]

In [25]:
correct_csv='_correct.csv'

In [26]:
mimic=[]

for x in range(0,class_number):
  number=str(x)
  file=first_part+number+correct_csv
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  b=len(a)
  total=b+incorrect_count_list[x]
  score=total/sample_size
  mimic.append(score)

In [27]:
mimic

[0.924, 0.8963, 0.9002, 0.9199, 0.9274, 0.9216, 0.9371, 0.9264, 0.9256, 0.9349]

In [28]:
average=sum(mimic)/class_number
average

0.92134