#Initialization

In [1]:
import pandas as pd
import numpy as np
#from google.colab import files

# Real Test Data

In [2]:
true = pd.read_csv ('TestingDataCifar100ResnetSize50.csv')

true

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,Class Label
0,0.173756,0.995893,-0.902762,0.824240,-1.225246,-0.217589,-0.120541,-0.267651,0.105222,1.011379,...,-0.527280,-0.030690,0.394633,0.166154,-2.163052,-0.754190,-1.340422,-1.443294,1.370429,49
1,-0.537903,-0.878381,-1.153254,0.658583,1.649681,-1.173530,1.768854,-0.964655,-0.265817,-0.621993,...,0.579289,0.363943,0.366032,0.060064,1.018853,-2.025079,0.440218,-0.936416,-0.987406,33
2,1.046454,-0.513176,-0.685783,-0.131831,-1.118063,0.035939,0.648038,-1.722898,-0.431523,-1.802559,...,-0.870894,1.090016,0.083242,-0.220804,-1.474400,-0.794525,-1.068113,-0.345201,-0.220334,72
3,0.875930,-0.201800,-1.627295,0.602200,0.228871,-3.000981,0.421379,-1.191603,1.106971,-0.737908,...,-0.178575,0.789839,-0.197662,-0.659653,-1.700615,-0.205200,1.001403,0.071651,-0.116147,51
4,1.404571,0.017656,0.634249,-0.233205,0.252195,-0.526458,-1.749922,-0.810481,0.828603,-0.161431,...,0.333275,-0.946271,-0.546709,-0.278491,-2.401822,-0.444465,0.099926,0.560477,-0.041747,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.081319,1.437741,-1.225815,-0.683269,1.257006,-0.468399,0.744128,-0.587319,0.547267,-1.227287,...,-0.924106,-0.240203,0.620737,-0.898024,0.230038,0.156096,0.413841,-1.251160,-0.029863,83
9996,0.360918,-1.095141,-0.267960,0.926793,0.529785,0.043188,0.669925,-1.812021,-0.055723,-1.093711,...,-0.746469,-1.154618,-0.879191,-1.004438,-1.189647,-0.395447,-0.684553,0.017531,1.263697,14
9997,0.577082,-1.163329,-0.048816,-0.534406,0.790386,0.491423,1.627443,-1.187413,-0.169197,-1.273646,...,0.538069,0.065293,-0.045603,-1.052141,-1.802577,-0.166397,-1.367178,-0.535000,0.298549,51
9998,0.459075,-0.465029,-1.047717,-0.863409,0.045892,-0.811884,-0.096894,-1.058827,-0.618814,-0.796933,...,0.171860,0.456040,1.077817,1.070139,-1.152239,0.230709,-0.264978,0.188771,-1.040385,42
9999,0.972025,-1.068403,-1.006560,0.068743,1.035108,-0.434975,1.202539,-1.216682,0.439613,-0.397698,...,-1.416500,0.418610,0.061586,-0.506907,-1.381515,-1.021078,0.166817,-1.753821,0.663580,70

In [3]:
ClassLabel="Class Label"
dataFeatures_true = true.drop(ClassLabel,axis = 1).values

r=len(dataFeatures_true)
dataFeatures_true=dataFeatures_true[:r]

In [4]:
dataPhenotypes_true = true[ClassLabel].values

In [5]:
iteration=len(dataFeatures_true[0])
sample_size=len(dataFeatures_true)

In [6]:
dataPhenotypes_true= dataPhenotypes_true[:r]

# Ruleset Dataframe

In [7]:
ruleset = pd.read_csv ('RulePopulationCifar100Resnet50LCS2.csv')

ruleset

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,#,"-1.05044625975,3.53438233175",#,"-1.7358484673599999,2.23700515536",#,#,"-1.66247402732,2.14501892532","-3.0968155405199997,1.71636231252","-0.83989821468,1.3810230346799999","-2.6229176742,1.2072271321999999",...,66,3.050000e-19,0.014077,2,6925.248038,49834,0,0.42,25,1776
1,#,#,#,#,#,#,#,"-2.88059832102,0.30650593301999995",#,#,...,80,2.120000e-19,0.013572,1,7317.085363,49852,1,0.36,159,11715
2,#,#,#,#,#,"-3.19602657811,0.5383265161100002","-2.4136790639999997,3.0778973099999996","-3.4643798499200003,0.047939123920000215","0.0032392122800000145,2.15685981772",#,...,30,3.630000e-06,0.285714,2,1402.984000,37402,2,0.42,2,7
3,"-1.1958696023800004,3.2314080363800004",#,"-1.3713586329999998,1.8835951089999998",#,#,"-1.173757135625,0.555110037625",#,"-2.4560306882800003,-0.11448470572000002",#,#,...,11,4.400000e-12,0.073171,2,8681.531355,14573,3,0.58,3,41
4,"-0.71835247044,3.9014155004399997","-0.691517645375,3.079873615375","-1.0087364806199997,2.96230708462","-1.37928335452,2.86291627652",#,#,"-1.503515959,2.1575349569999998",#,#,"-2.2277963585,1.0637343345000003",...,59,2.030000e-14,0.042735,2,8931.385159,49600,4,0.54,10,234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91178,#,#,#,#,"-5.275862921914147,2.8912793055500003",#,#,#,#,#,...,43,5.280000e-08,0.225000,1,6910.447166,49997,49997,0.30,0,0
91179,"-1.37093912578,1.29530087346",#,#,#,#,#,#,"-2.76807872806,0.28893963806","-1.1271682495999997,2.9108703856",#,...,59,1.470000e-08,0.166667,1,7253.222383,49998,49998,0.28,0,0
91180,"-1.37093912578,1.29530087346","-2.8429275269999996,0.8877110483750001",#,#,#,"-2.6080497837150003,0.9188392497150001","-2.23840355392,2.30129958192",#,#,#,...,59,1.470000e-08,0.166667,1,7231.054274,49998,49998,0.32,0,0
91181,#,#,#,#,#,#,#,#,#,#,...,18,6.810000e-16,0.036879,1,7579.123891,49999,49999,0.32,0,0
91182,#,"-5.860247487854274,1.1218674124999999",#,#,#,"-2.2233541381800004,1.3726895821800003",#,#,#,#,...,18,6.810000e-16,0.036879,1,7200.329551,49999,49999,0.30,0,0

In [8]:
ruleset2=ruleset.replace("#",np.nan)

In [9]:
ruleset3=ruleset2.replace(np.nan,0)

In [10]:
ruleset3

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,0,"-1.05044625975,3.53438233175",0,"-1.7358484673599999,2.23700515536",0,0,"-1.66247402732,2.14501892532","-3.0968155405199997,1.71636231252","-0.83989821468,1.3810230346799999","-2.6229176742,1.2072271321999999",...,66,3.050000e-19,0.014077,2,6925.248038,49834,0,0.42,25,1776
1,0,0,0,0,0,0,0,"-2.88059832102,0.30650593301999995",0,0,...,80,2.120000e-19,0.013572,1,7317.085363,49852,1,0.36,159,11715
2,0,0,0,0,0,"-3.19602657811,0.5383265161100002","-2.4136790639999997,3.0778973099999996","-3.4643798499200003,0.047939123920000215","0.0032392122800000145,2.15685981772",0,...,30,3.630000e-06,0.285714,2,1402.984000,37402,2,0.42,2,7
3,"-1.1958696023800004,3.2314080363800004",0,"-1.3713586329999998,1.8835951089999998",0,0,"-1.173757135625,0.555110037625",0,"-2.4560306882800003,-0.11448470572000002",0,0,...,11,4.400000e-12,0.073171,2,8681.531355,14573,3,0.58,3,41
4,"-0.71835247044,3.9014155004399997","-0.691517645375,3.079873615375","-1.0087364806199997,2.96230708462","-1.37928335452,2.86291627652",0,0,"-1.503515959,2.1575349569999998",0,0,"-2.2277963585,1.0637343345000003",...,59,2.030000e-14,0.042735,2,8931.385159,49600,4,0.54,10,234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91178,0,0,0,0,"-5.275862921914147,2.8912793055500003",0,0,0,0,0,...,43,5.280000e-08,0.225000,1,6910.447166,49997,49997,0.30,0,0
91179,"-1.37093912578,1.29530087346",0,0,0,0,0,0,"-2.76807872806,0.28893963806","-1.1271682495999997,2.9108703856",0,...,59,1.470000e-08,0.166667,1,7253.222383,49998,49998,0.28,0,0
91180,"-1.37093912578,1.29530087346","-2.8429275269999996,0.8877110483750001",0,0,0,"-2.6080497837150003,0.9188392497150001","-2.23840355392,2.30129958192",0,0,0,...,59,1.470000e-08,0.166667,1,7231.054274,49998,49998,0.32,0,0
91181,0,0,0,0,0,0,0,0,0,0,...,18,6.810000e-16,0.036879,1,7579.123891,49999,49999,0.32,0,0
91182,0,"-5.860247487854274,1.1218674124999999",0,0,0,"-2.2233541381800004,1.3726895821800003",0,0,0,0,...,18,6.810000e-16,0.036879,1,7200.329551,49999,49999,0.30,0,0

In [11]:
Extra=['phenotype','Fitness','Accuracy','Numerosity','Avg Match Set Size','TimeStamp GA','Iteration Initialized','Specificity','Correct Count','Match Count']

In [12]:
correct=Extra[8]

In [13]:
#ruleset1
#Features = ruleset.drop(Extra,axis = 1).columns.values

#ruleset2
#Features = ruleset2.drop(Extra,axis = 1).columns.values

#ruleset3
Features = ruleset3.drop(Extra,axis = 1).columns.values
Feature_count=len(Features)

print(Feature_count)
Features

50

array(['N0', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'N11', 'N12', 'N13', 'N14', 'N15', 'N16', 'N17', 'N18', 'N19',
       'N20', 'N21', 'N22', 'N23', 'N24', 'N25', 'N26', 'N27', 'N28',
       'N29', 'N30', 'N31', 'N32', 'N33', 'N34', 'N35', 'N36', 'N37',
       'N38', 'N39', 'N40', 'N41', 'N42', 'N43', 'N44', 'N45', 'N46',
       'N47', 'N48', 'N49'], dtype=object)

#New Ruleset

In [14]:
high="_high"
low="_low"

In [15]:
for x in range(0,Feature_count):

  feature_name=Features[x]

  if x==0:
    index_count_l=0
    index_count_h=1

  else:
    index_count_l=2*x
    index_count_h=index_count_l+1

  split_column=ruleset3[feature_name].str.split(',', expand=True)

  feature_name_low=feature_name+low
  feature_name_high=feature_name+high

  ruleset3.insert(index_count_l,feature_name_low,split_column[0])
  ruleset3.insert(index_count_h,feature_name_high,split_column[1])

  ruleset3=ruleset3.drop(columns=feature_name)

In [16]:
ruleset3=ruleset3.replace(np.nan,0)

In [17]:
ruleset3

,N0_low,N0_high,N1_low,N1_high,N2_low,N2_high,N3_low,N3_high,N4_low,N4_high,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,0,0,-1.05044625975,3.53438233175,0,0,-1.7358484673599999,2.23700515536,0,0,...,66,3.050000e-19,0.014077,2,6925.248038,49834,0,0.42,25,1776
1,0,0,0,0,0,0,0,0,0,0,...,80,2.120000e-19,0.013572,1,7317.085363,49852,1,0.36,159,11715
2,0,0,0,0,0,0,0,0,0,0,...,30,3.630000e-06,0.285714,2,1402.984000,37402,2,0.42,2,7
3,-1.1958696023800004,3.2314080363800004,0,0,-1.3713586329999998,1.8835951089999998,0,0,0,0,...,11,4.400000e-12,0.073171,2,8681.531355,14573,3,0.58,3,41
4,-0.71835247044,3.9014155004399997,-0.691517645375,3.079873615375,-1.0087364806199997,2.96230708462,-1.37928335452,2.86291627652,0,0,...,59,2.030000e-14,0.042735,2,8931.385159,49600,4,0.54,10,234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91178,0,0,0,0,0,0,0,0,-5.275862921914147,2.8912793055500003,...,43,5.280000e-08,0.225000,1,6910.447166,49997,49997,0.30,0,0
91179,-1.37093912578,1.29530087346,0,0,0,0,0,0,0,0,...,59,1.470000e-08,0.166667,1,7253.222383,49998,49998,0.28,0,0
91180,-1.37093912578,1.29530087346,-2.8429275269999996,0.8877110483750001,0,0,0,0,0,0,...,59,1.470000e-08,0.166667,1,7231.054274,49998,49998,0.32,0,0
91181,0,0,0,0,0,0,0,0,0,0,...,18,6.810000e-16,0.036879,1,7579.123891,49999,49999,0.32,0,0
91182,0,0,-5.860247487854274,1.1218674124999999,0,0,0,0,0,0,...,18,6.810000e-16,0.036879,1,7200.329551,49999,49999,0.30,0,0

In [18]:
Features_1 = ruleset3.drop(Extra,axis = 1).columns.values
Features_1

array(['N0_low', 'N0_high', 'N1_low', 'N1_high', 'N2_low', 'N2_high',
       'N3_low', 'N3_high', 'N4_low', 'N4_high', 'N5_low', 'N5_high',
       'N6_low', 'N6_high', 'N7_low', 'N7_high', 'N8_low', 'N8_high',
       'N9_low', 'N9_high', 'N10_low', 'N10_high', 'N11_low', 'N11_high',
       'N12_low', 'N12_high', 'N13_low', 'N13_high', 'N14_low',
       'N14_high', 'N15_low', 'N15_high', 'N16_low', 'N16_high',
       'N17_low', 'N17_high', 'N18_low', 'N18_high', 'N19_low',
       'N19_high', 'N20_low', 'N20_high', 'N21_low', 'N21_high',
       'N22_low', 'N22_high', 'N23_low', 'N23_high', 'N24_low',
       'N24_high', 'N25_low', 'N25_high', 'N26_low', 'N26_high',
       'N27_low', 'N27_high', 'N28_low', 'N28_high', 'N29_low',
       'N29_high', 'N30_low', 'N30_high', 'N31_low', 'N31_high',
       'N32_low', 'N32_high', 'N33_low', 'N33_high', 'N34_low',
       'N34_high', 'N35_low', 'N35_high', 'N36_low', 'N36_high',
       'N37_low', 'N37_high', 'N38_low', 'N38_high', 'N39_low',
       'N39_high', 'N40_low', 'N40_high', 'N41_low', 'N41_high',
       'N42_low', 'N42_high', 'N43_low', 'N43_high', 'N44_low',
       'N44_high', 'N45_low', 'N45_high', 'N46_low', 'N46_high',
       'N47_low', 'N47_high', 'N48_low', 'N48_high', 'N49_low',
       'N49_high'], dtype=object)

#code

In [19]:
#number of classes
class_number=100

#enter first part of the file name here

#Google colab example: '/content/first part of file name_'
#first_part='/content/Vgg19_cifar10_50_shared_class_'

#non google colab:'first part of file name
first_part='Resnet_cifar100_50_shared_class_'

#last part of file name
incorrect='_incorrect.csv'
instance_list=[]

In [20]:
for x in range(0,class_number):
  number=str(x)
  file=first_part+number+incorrect
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  instance_list.append(a)

In [21]:
dataFeatures_true[0]

array([ 0.17375642,  0.99589294, -0.9027617 ,  0.82424021, -1.22524643,
       -0.21758939, -0.12054117, -0.26765057,  0.10522207,  1.01137924,
        1.05745745, -2.43879533, -0.0487664 ,  0.44157022,  0.4549576 ,
        2.05541015,  0.21902707, -0.05389182, -1.94180524,  0.01183584,
        1.42890906,  0.19896095,  0.40417671, -1.40644217,  1.80241168,
       -1.79947794,  0.26489928, -1.305547  , -0.27289963, -1.55286455,
       -0.24984392,  2.00638819, -1.0691297 ,  0.61910969, -1.80716837,
        0.20864159,  0.16382189,  1.08683646,  1.07146394,  1.25614035,
        1.07432222, -0.52728009, -0.03069027,  0.39463273,  0.16615365,
       -2.16305161, -0.75419039, -1.34042203, -1.44329429,  1.37042856])

In [22]:
for feature in range(iteration):
  print(feature)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [23]:
incorrect_count_list=[]
ml='_LCS'

for x in range(0,class_number):

  incorrect_count=0

  #new class list
  b=instance_list[x]
  

  for y in b:

    #instance for class
    z=y[0]

    #filter ruleset by class
    class_check=dataPhenotypes_true[z-1]
    ruleset_filter= ruleset3[ruleset3['phenotype'] == class_check]
    
    #converts string to float
    ruleset_filter2=ruleset_filter.astype(float)


    #Checks feature for each rule in class
    for feature in range(iteration):
      f=dataFeatures_true[z-1][feature]

      #lowest range for feature
      l=2*feature

      #highest range for feature
      h=l+1

      #low feature name
      Low=Features_1[l]

      #high feature name
      High=Features_1[h]

      #when the count starts at 0
      if feature==0:
        ruleset_filter_test= ruleset_filter2[((ruleset_filter2[Low] < f)&(ruleset_filter2[High] >= f)) | (ruleset_filter2[High] == 0) ]
      
      #when the feature count is not 0
      else:
        ruleset_filter_test= ruleset_filter_test[((ruleset_filter_test[Low] < f)&(ruleset_filter_test[High] >= f)) | (ruleset_filter_test[High] == 0) ]
    
    #filters out all of the rows that have a correct count of zero
    ruleset_filter_test2= ruleset_filter_test[ruleset_filter_test[correct] != 0 ]

    #replaces 0 with #
    ruleset_filter_test3=ruleset_filter_test2.replace(0,'#')

    #adds
    if ruleset_filter_test3.empty:
      continue
    else:
      file_2=str(iteration)+'_class_'+str(class_check)+'_iteration_'+str(z)+'_'+ml+'.csv'
      ruleset_filter_test3.to_csv(file_2, index=False) 
      #files.download(file_2)
      incorrect_count+=1
    
  incorrect_count_list.append(incorrect_count)

In [24]:
incorrect_count_list

[55,
 88,
 95,
 100,
 99,
 96,
 80,
 96,
 86,
 91,
 98,
 73,
 95,
 98,
 97,
 83,
 86,
 98,
 93,
 99,
 58,
 97,
 92,
 86,
 73,
 98,
 88,
 100,
 77,
 97,
 96,
 83,
 100,
 88,
 98,
 99,
 95,
 99,
 95,
 81,
 98,
 79,
 87,
 79,
 98,
 99,
 97,
 98,
 65,
 99,
 100,
 98,
 79,
 35,
 94,
 100,
 93,
 98,
 92,
 99,
 77,
 51,
 71,
 95,
 99,
 98,
 100,
 86,
 87,
 99,
 95,
 63,
 100,
 85,
 100,
 100,
 68,
 100,
 81,
 98,
 100,
 90,
 47,
 97,
 100,
 98,
 94,
 57,
 97,
 95,
 98,
 98,
 95,
 98,
 58,
 88,
 84,
 98,
 99,
 72]

In [25]:
correct_csv='_correct.csv'

In [26]:
mimic=[]

for x in range(0,class_number):
  number=str(x)
  file=first_part+number+correct_csv
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  b=len(a)
  total=b+incorrect_count_list[x]
  score=total/sample_size
  mimic.append(score)

In [27]:
mimic

[0.9549,
 0.9933,
 0.9972,
 0.9998,
 0.9998,
 0.9917,
 0.9899,
 0.9983,
 0.9911,
 0.9946,
 0.9992,
 0.9484,
 0.9923,
 0.9956,
 0.9915,
 0.9871,
 0.9919,
 0.9981,
 0.9972,
 0.9978,
 0.9808,
 0.9992,
 0.9973,
 0.988,
 0.9897,
 0.9994,
 0.9768,
 0.9991,
 0.9907,
 0.9972,
 0.9921,
 0.9842,
 1.0,
 0.9945,
 0.9976,
 0.9962,
 0.9971,
 0.9995,
 0.9926,
 0.9959,
 0.9911,
 0.9884,
 0.9913,
 0.9571,
 0.9983,
 0.9998,
 0.9989,
 0.9977,
 0.9806,
 0.999,
 0.9997,
 0.996,
 0.975,
 0.9541,
 0.9948,
 1.0,
 0.9971,
 0.9986,
 0.9962,
 0.9958,
 0.9931,
 0.9612,
 0.9773,
 0.9919,
 0.9981,
 0.9997,
 0.9973,
 0.9866,
 0.9801,
 0.9962,
 0.9959,
 0.9821,
 0.9999,
 0.9859,
 0.9999,
 0.9952,
 0.9758,
 0.9994,
 0.9954,
 0.9975,
 0.9996,
 0.9918,
 0.9642,
 0.9984,
 0.9996,
 0.9994,
 0.997,
 0.9727,
 0.9979,
 0.9853,
 0.9997,
 0.9994,
 0.9924,
 0.998,
 0.9734,
 0.9774,
 0.9501,
 0.993,
 0.9967,
 0.9899]

In [28]:
average=sum(mimic)/class_number
average

0.9907150000000002