#Initialization

In [28]:
import pandas as pd
import numpy as np
#from google.colab import files

# Real Test Data

In [29]:
true = pd.read_csv ('TestingDataCifar10ResnetSize50.csv')

true

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,Class Label
0,0.045984,-1.809093,0.962786,3.040143,-1.046193,1.561378,-0.301810,-0.523576,-1.277382,-0.033236,...,-0.552937,0.635205,-0.922971,-0.660693,-0.705068,0.867965,-1.651459,-0.769704,-1.023028,3
1,-0.351932,-2.402908,0.967221,-0.108375,-0.110304,1.728799,-0.565269,0.771335,-1.382652,0.084307,...,0.324672,0.740268,0.262936,1.221302,0.717881,1.123806,-0.351116,-0.964519,-0.480314,8
2,-0.010701,-0.552145,1.341478,1.715292,0.292767,-0.390069,-0.504548,-0.666088,-0.488765,-0.447521,...,0.442408,0.496378,0.214534,-0.085056,1.293700,0.294916,-1.908343,-0.684419,1.037418,8
3,0.379253,-1.182422,0.075239,0.648609,-0.376217,1.351790,0.068080,0.210757,0.491276,0.616011,...,-1.142415,0.326709,0.185790,-0.176350,1.588946,0.465095,-1.093750,-0.050963,0.701707,0
4,0.598469,-0.122648,0.326211,-0.098662,0.682595,0.035594,0.792485,-0.518497,-0.740589,0.091855,...,-0.734268,-1.476978,-0.468438,0.060300,1.250476,1.205960,-1.039965,-1.094175,1.037836,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.130824,-1.274692,1.285204,1.889008,-0.050886,1.718586,0.237420,-0.117587,-1.020881,-0.196550,...,0.291533,1.016304,0.502513,-0.655314,0.703502,0.869025,-1.614717,-0.757435,-0.303849,8
9996,-0.651160,-1.208278,0.517278,1.023506,-0.392711,-0.353128,1.679403,-0.033505,0.310703,1.086639,...,-0.902508,0.173146,-1.881030,0.721825,0.677478,1.605750,-1.373115,-0.609340,-0.160901,3
9997,0.476687,-0.157761,0.126607,1.873811,-0.174550,0.207434,0.395595,-0.669925,-0.268797,-0.514459,...,-0.096004,-0.396460,0.260516,0.038161,0.545210,0.427313,0.011896,-1.478913,0.256117,5
9998,-0.120238,-1.125783,0.894694,0.558443,-0.653700,0.676805,1.650803,-0.234050,-1.124739,-0.094457,...,0.801711,-0.992513,0.450320,2.346105,1.717489,-0.926430,-0.523988,-1.776059,-0.814363,1
9999,-0.403236,-0.045679,0.476404,0.583297,-0.568949,2.615918,-0.086044,0.318214,0.262237,-0.451109,...,-0.605702,0.863703,-1.004675,0.394701,1.163875,1.057020,-0.577890,-0.779816,-0.736490,7

In [30]:
ClassLabel="Class Label"
dataFeatures_true = true.drop(ClassLabel,axis = 1).values

r=len(dataFeatures_true)
dataFeatures_true=dataFeatures_true[:r]

In [31]:
dataPhenotypes_true = true[ClassLabel].values

In [32]:
iteration=len(dataFeatures_true[0])
sample_size=len(dataFeatures_true)

In [33]:
dataPhenotypes_true= dataPhenotypes_true[:r]

# Ruleset Dataframe

In [34]:
ruleset = pd.read_csv ('RulePopulationCifar10Resnet50LCS2.csv')

ruleset

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,"-1.06930848,0.30079922",#,#,#,"-1.6035588390000002,0.632202039","-1.692472495,2.204617175","-0.9033837954999998,1.8802210754999997",#,"-1.247105462,2.328448162","-1.195604175,1.395303795",...,1,5.370000e-08,0.187500,2,33.312607,337,0,0.60,3,16
1,#,"-2.1700897780000004,-0.462076822","0.16675585799999992,2.4771825420000004",#,#,#,#,#,#,"-1.1647179850000002,2.659955685",...,7,2.470000e-11,0.086957,1,32.690970,372,1,0.38,2,23
2,#,#,"-1.6077066255,0.2534704255000001","-1.5253810460000001,1.792120986","-1.6251515990000003,2.3304253390000005",#,"-1.0089056605,2.4220491805",#,"-1.5783904549999999,0.904632895",#,...,1,1.000000e+00,1.000000,1,1.000000,2,2,0.52,1,1
3,#,"-2.619599096,-0.517429304",#,#,"-1.2046563449999999,1.203086139",#,"-1.0382227249999998,2.198527125","-2.288881728,-0.10805827199999984","-2.425390676,0.35559547599999997","-0.8486052749999999,1.495549555",...,1,3.540000e-09,0.142857,1,12.248000,3,3,0.44,1,7
4,"-1.9524001000000002,0.9986011000000001","-2.760985202,-0.527429798","-0.02629399400000021,3.3109889940000006",#,#,"0.3506429499999999,1.95218665",#,#,"-1.683891601,1.593699221",#,...,7,8.101311e-02,0.777778,1,22.965760,499,4,0.44,7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,#,#,#,"-0.5533392480000001,3.019355248",#,"0.28118802499999984,2.6835035750000005",#,"-2.0889591320000003,0.7833449320000001",#,#,...,1,0.000000e+00,0.000000,1,41.500000,496,496,0.24,0,2
596,#,#,"0.013680729999999919,3.86439187",#,"-1.3612358370000002,1.9064146770000003",#,#,"-1.6772568039999998,0.3439942039999998",#,"-0.1265625025,1.9091509025",...,2,1.000000e+00,1.000000,1,6.000000,497,497,0.42,1,1
597,"-2.8028421999999997,0.35894479999999995","-3.3758095920000004,0.8285299920000002","-2.5220312424999998,2.2913576825","-0.6208118020000002,3.781258202","-1.685592484,0.8368044040000002","-0.3519673750000002,2.0503481750000003","-0.5531520164999999,1.3241628964999999",#,#,#,...,8,1.690000e-06,0.333333,1,39.270080,498,498,0.52,0,0
598,"-1.9524001000000002,0.9986011000000001",#,"-0.02629399400000021,3.3109889940000006",#,#,"0.3506429499999999,1.95218665",#,#,"-1.683891601,1.593699221",#,...,7,8.101311e-03,0.777778,1,22.965760,499,499,0.46,0,0
599,"-1.9524001000000002,0.9986011000000001","-2.760985202,-0.527429798",#,"-1.8204554880000001,2.390220168",#,"0.3506429499999999,1.95218665",#,#,"-1.683891601,1.593699221",#,...,7,3.457161e-03,0.714286,1,26.432000,499,499,0.44,0,0

In [35]:
ruleset2=ruleset.replace("#",np.nan)

In [36]:
ruleset3=ruleset2.replace(np.nan,0)

In [37]:
ruleset3

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,"-1.06930848,0.30079922",0,0,0,"-1.6035588390000002,0.632202039","-1.692472495,2.204617175","-0.9033837954999998,1.8802210754999997",0,"-1.247105462,2.328448162","-1.195604175,1.395303795",...,1,5.370000e-08,0.187500,2,33.312607,337,0,0.60,3,16
1,0,"-2.1700897780000004,-0.462076822","0.16675585799999992,2.4771825420000004",0,0,0,0,0,0,"-1.1647179850000002,2.659955685",...,7,2.470000e-11,0.086957,1,32.690970,372,1,0.38,2,23
2,0,0,"-1.6077066255,0.2534704255000001","-1.5253810460000001,1.792120986","-1.6251515990000003,2.3304253390000005",0,"-1.0089056605,2.4220491805",0,"-1.5783904549999999,0.904632895",0,...,1,1.000000e+00,1.000000,1,1.000000,2,2,0.52,1,1
3,0,"-2.619599096,-0.517429304",0,0,"-1.2046563449999999,1.203086139",0,"-1.0382227249999998,2.198527125","-2.288881728,-0.10805827199999984","-2.425390676,0.35559547599999997","-0.8486052749999999,1.495549555",...,1,3.540000e-09,0.142857,1,12.248000,3,3,0.44,1,7
4,"-1.9524001000000002,0.9986011000000001","-2.760985202,-0.527429798","-0.02629399400000021,3.3109889940000006",0,0,"0.3506429499999999,1.95218665",0,0,"-1.683891601,1.593699221",0,...,7,8.101311e-02,0.777778,1,22.965760,499,4,0.44,7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,0,0,0,"-0.5533392480000001,3.019355248",0,"0.28118802499999984,2.6835035750000005",0,"-2.0889591320000003,0.7833449320000001",0,0,...,1,0.000000e+00,0.000000,1,41.500000,496,496,0.24,0,2
596,0,0,"0.013680729999999919,3.86439187",0,"-1.3612358370000002,1.9064146770000003",0,0,"-1.6772568039999998,0.3439942039999998",0,"-0.1265625025,1.9091509025",...,2,1.000000e+00,1.000000,1,6.000000,497,497,0.42,1,1
597,"-2.8028421999999997,0.35894479999999995","-3.3758095920000004,0.8285299920000002","-2.5220312424999998,2.2913576825","-0.6208118020000002,3.781258202","-1.685592484,0.8368044040000002","-0.3519673750000002,2.0503481750000003","-0.5531520164999999,1.3241628964999999",0,0,0,...,8,1.690000e-06,0.333333,1,39.270080,498,498,0.52,0,0
598,"-1.9524001000000002,0.9986011000000001",0,"-0.02629399400000021,3.3109889940000006",0,0,"0.3506429499999999,1.95218665",0,0,"-1.683891601,1.593699221",0,...,7,8.101311e-03,0.777778,1,22.965760,499,499,0.46,0,0
599,"-1.9524001000000002,0.9986011000000001","-2.760985202,-0.527429798",0,"-1.8204554880000001,2.390220168",0,"0.3506429499999999,1.95218665",0,0,"-1.683891601,1.593699221",0,...,7,3.457161e-03,0.714286,1,26.432000,499,499,0.44,0,0

In [38]:
Extra=['phenotype','Fitness','Accuracy','Numerosity','Avg Match Set Size','TimeStamp GA','Iteration Initialized','Specificity','Correct Count','Match Count']

In [39]:
correct=Extra[8]

In [40]:
#ruleset1
#Features = ruleset.drop(Extra,axis = 1).columns.values

#ruleset2
#Features = ruleset2.drop(Extra,axis = 1).columns.values

#ruleset3
Features = ruleset3.drop(Extra,axis = 1).columns.values
Feature_count=len(Features)

print(Feature_count)
Features

50

array(['N0', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'N11', 'N12', 'N13', 'N14', 'N15', 'N16', 'N17', 'N18', 'N19',
       'N20', 'N21', 'N22', 'N23', 'N24', 'N25', 'N26', 'N27', 'N28',
       'N29', 'N30', 'N31', 'N32', 'N33', 'N34', 'N35', 'N36', 'N37',
       'N38', 'N39', 'N40', 'N41', 'N42', 'N43', 'N44', 'N45', 'N46',
       'N47', 'N48', 'N49'], dtype=object)

#New Ruleset

In [41]:
high="_high"
low="_low"

In [42]:
for x in range(0,Feature_count):

  feature_name=Features[x]

  if x==0:
    index_count_l=0
    index_count_h=1

  else:
    index_count_l=2*x
    index_count_h=index_count_l+1

  split_column=ruleset3[feature_name].str.split(',', expand=True)

  feature_name_low=feature_name+low
  feature_name_high=feature_name+high

  ruleset3.insert(index_count_l,feature_name_low,split_column[0])
  ruleset3.insert(index_count_h,feature_name_high,split_column[1])

  ruleset3=ruleset3.drop(columns=feature_name)

In [43]:
ruleset3=ruleset3.replace(np.nan,0)

In [44]:
ruleset3

,N0_low,N0_high,N1_low,N1_high,N2_low,N2_high,N3_low,N3_high,N4_low,N4_high,...,phenotype,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Correct Count,Match Count
0,-1.06930848,0.30079922,0,0,0,0,0,0,-1.6035588390000002,0.632202039,...,1,5.370000e-08,0.187500,2,33.312607,337,0,0.60,3,16
1,0,0,-2.1700897780000004,-0.462076822,0.16675585799999992,2.4771825420000004,0,0,0,0,...,7,2.470000e-11,0.086957,1,32.690970,372,1,0.38,2,23
2,0,0,0,0,-1.6077066255,0.2534704255000001,-1.5253810460000001,1.792120986,-1.6251515990000003,2.3304253390000005,...,1,1.000000e+00,1.000000,1,1.000000,2,2,0.52,1,1
3,0,0,-2.619599096,-0.517429304,0,0,0,0,-1.2046563449999999,1.203086139,...,1,3.540000e-09,0.142857,1,12.248000,3,3,0.44,1,7
4,-1.9524001000000002,0.9986011000000001,-2.760985202,-0.527429798,-0.02629399400000021,3.3109889940000006,0,0,0,0,...,7,8.101311e-02,0.777778,1,22.965760,499,4,0.44,7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,0,0,0,0,0,0,-0.5533392480000001,3.019355248,0,0,...,1,0.000000e+00,0.000000,1,41.500000,496,496,0.24,0,2
596,0,0,0,0,0.013680729999999919,3.86439187,0,0,-1.3612358370000002,1.9064146770000003,...,2,1.000000e+00,1.000000,1,6.000000,497,497,0.42,1,1
597,-2.8028421999999997,0.35894479999999995,-3.3758095920000004,0.8285299920000002,-2.5220312424999998,2.2913576825,-0.6208118020000002,3.781258202,-1.685592484,0.8368044040000002,...,8,1.690000e-06,0.333333,1,39.270080,498,498,0.52,0,0
598,-1.9524001000000002,0.9986011000000001,0,0,-0.02629399400000021,3.3109889940000006,0,0,0,0,...,7,8.101311e-03,0.777778,1,22.965760,499,499,0.46,0,0
599,-1.9524001000000002,0.9986011000000001,-2.760985202,-0.527429798,0,0,-1.8204554880000001,2.390220168,0,0,...,7,3.457161e-03,0.714286,1,26.432000,499,499,0.44,0,0

In [45]:
Features_1 = ruleset3.drop(Extra,axis = 1).columns.values
Features_1

array(['N0_low', 'N0_high', 'N1_low', 'N1_high', 'N2_low', 'N2_high',
       'N3_low', 'N3_high', 'N4_low', 'N4_high', 'N5_low', 'N5_high',
       'N6_low', 'N6_high', 'N7_low', 'N7_high', 'N8_low', 'N8_high',
       'N9_low', 'N9_high', 'N10_low', 'N10_high', 'N11_low', 'N11_high',
       'N12_low', 'N12_high', 'N13_low', 'N13_high', 'N14_low',
       'N14_high', 'N15_low', 'N15_high', 'N16_low', 'N16_high',
       'N17_low', 'N17_high', 'N18_low', 'N18_high', 'N19_low',
       'N19_high', 'N20_low', 'N20_high', 'N21_low', 'N21_high',
       'N22_low', 'N22_high', 'N23_low', 'N23_high', 'N24_low',
       'N24_high', 'N25_low', 'N25_high', 'N26_low', 'N26_high',
       'N27_low', 'N27_high', 'N28_low', 'N28_high', 'N29_low',
       'N29_high', 'N30_low', 'N30_high', 'N31_low', 'N31_high',
       'N32_low', 'N32_high', 'N33_low', 'N33_high', 'N34_low',
       'N34_high', 'N35_low', 'N35_high', 'N36_low', 'N36_high',
       'N37_low', 'N37_high', 'N38_low', 'N38_high', 'N39_low',
       'N39_high', 'N40_low', 'N40_high', 'N41_low', 'N41_high',
       'N42_low', 'N42_high', 'N43_low', 'N43_high', 'N44_low',
       'N44_high', 'N45_low', 'N45_high', 'N46_low', 'N46_high',
       'N47_low', 'N47_high', 'N48_low', 'N48_high', 'N49_low',
       'N49_high'], dtype=object)

#code

In [46]:
#number of classes
class_number=10

#enter first part of the file name here

#Google colab example: '/content/first part of file name_'
#first_part='/content/Vgg19_cifar10_50_shared_class_'

#non google colab:'first part of file name
first_part='Resnet_cifar10_50_shared_class_'

#last part of file name
incorrect='_incorrect.csv'
instance_list=[]

In [47]:
for x in range(0,class_number):
  number=str(x)
  file=first_part+number+incorrect
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  instance_list.append(a)

In [48]:
dataFeatures_true[0]

array([ 0.04598381, -1.8090932 ,  0.96278596,  3.040143  , -1.0461934 ,
        1.5613775 , -0.3018096 , -0.5235757 , -1.277382  , -0.03323633,
       -0.8186503 , -1.6650954 , -0.9858822 , -0.10338689, -0.548602  ,
       -0.82007474,  0.9963667 , -0.17942584, -0.74817914,  1.4768425 ,
        0.30922094, -0.4724149 ,  1.110893  ,  0.75635296,  1.3067633 ,
       -0.5343775 ,  0.93735915, -1.6132408 , -0.04742826,  0.8854627 ,
       -0.8799882 , -0.14661467, -0.23297158, -1.4818187 ,  0.19696257,
       -0.61248296,  0.81233203,  0.6048396 , -1.0428531 , -0.53597224,
       -0.69763255, -0.5529368 ,  0.6352051 , -0.92297065, -0.6606927 ,
       -0.70506775,  0.8679652 , -1.6514589 , -0.7697039 , -1.0230278 ])

In [49]:
for feature in range(iteration):
  print(feature)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [50]:
incorrect_count_list=[]
ml='_LCS'

for x in range(0,class_number):

  incorrect_count=0

  #new class list
  b=instance_list[x]
  

  for y in b:

    #instance for class
    z=y[0]

    #filter ruleset by class
    class_check=dataPhenotypes_true[z-1]
    ruleset_filter= ruleset3[ruleset3['phenotype'] == class_check]
    
    #converts string to float
    ruleset_filter2=ruleset_filter.astype(float)


    #Checks feature for each rule in class
    for feature in range(iteration):
      f=dataFeatures_true[z-1][feature]

      #lowest range for feature
      l=2*feature

      #highest range for feature
      h=l+1

      #low feature name
      Low=Features_1[l]

      #high feature name
      High=Features_1[h]

      #when the count starts at 0
      if feature==0:
        ruleset_filter_test= ruleset_filter2[((ruleset_filter2[Low] < f)&(ruleset_filter2[High] >= f)) | (ruleset_filter2[High] == 0) ]
      
      #when the feature count is not 0
      else:
        ruleset_filter_test= ruleset_filter_test[((ruleset_filter_test[Low] < f)&(ruleset_filter_test[High] >= f)) | (ruleset_filter_test[High] == 0) ]
    
    #filters out all of the rows that have a correct count of zero
    ruleset_filter_test2= ruleset_filter_test[ruleset_filter_test[correct] != 0 ]

    #replaces 0 with #
    ruleset_filter_test3=ruleset_filter_test2.replace(0,'#')

    #adds
    if ruleset_filter_test3.empty:
      continue
    else:
      file_2=str(iteration)+'_class_'+str(class_check)+'_iteration_'+str(z)+'_'+ml+'.csv'
      ruleset_filter_test3.to_csv(file_2, index=False) 
      #files.download(file_2)
      incorrect_count+=1
    
  incorrect_count_list.append(incorrect_count)

In [51]:
incorrect_count_list

[205, 367, 342, 434, 375, 356, 328, 283, 390, 322]

In [52]:
correct_csv='_correct.csv'

In [53]:
mimic=[]

for x in range(0,class_number):
  number=str(x)
  file=first_part+number+correct_csv
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  b=len(a)
  total=b+incorrect_count_list[x]
  score=total/sample_size
  mimic.append(score)

In [54]:
mimic

[0.8652, 0.822, 0.8656, 0.8618, 0.8807, 0.8327, 0.8837, 0.8738, 0.8285, 0.8361]

In [55]:
average=sum(mimic)/class_number
average

0.85501