#Initialization

In [1]:
import pandas as pd
import numpy as np
#from google.colab import files

# Real Test Data

In [2]:
true = pd.read_csv ('TestingDataCifar100ResnetSize100.csv')

true

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Class Label
0,-0.160710,-0.118609,1.364182,-3.325208,-1.519649,0.455779,-2.368366,0.711584,-1.015519,-0.540396,...,-0.997015,-0.432137,0.018045,-0.701094,-0.233964,-0.722854,0.857195,-1.502313,0.909890,49
1,0.166452,0.334963,-0.213449,-0.846047,0.630586,-0.184569,-0.853100,0.263814,-0.956922,0.208006,...,-1.218204,0.856852,1.295395,-1.027848,-0.629634,-0.013735,-0.090077,0.581602,1.232205,33
2,0.558582,1.541446,0.397468,-2.492163,-0.776286,-0.098033,-0.708430,1.013817,-1.994095,-0.164143,...,-1.367378,0.260213,-1.254812,-1.019176,0.404925,-0.490913,-1.427422,-1.159136,1.676397,72
3,-0.207472,-0.117936,-0.279227,-2.071902,-1.116088,2.926582,0.089361,1.457731,-2.067014,1.217302,...,-0.300344,1.096133,0.122310,-1.119434,0.849269,0.725462,-0.364626,-1.102366,0.726545,51
4,1.018068,1.039858,0.896169,-0.375297,0.397201,1.832428,0.377811,1.700094,-0.980878,0.240338,...,-0.239863,-0.530352,-0.045193,-1.505260,-0.311110,0.045485,0.112012,-0.648987,0.509994,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.076635,0.128861,0.882215,0.183218,-0.100091,-0.329994,0.648205,1.072088,-0.696533,-0.506947,...,0.302830,0.352557,0.059254,-0.353694,1.226194,-0.259535,-0.362925,-0.848427,0.129941,83
9996,0.209159,-0.328338,-0.272969,-1.343403,-0.561781,0.201596,-0.095458,1.638071,-1.109241,0.359949,...,-0.654858,-0.143863,0.308334,-0.627006,-0.975449,-0.030572,1.510267,-0.382810,0.320475,14
9997,-0.498463,0.328677,-0.035722,-1.859716,-0.216455,-0.067376,-1.321650,-0.028579,-0.586226,0.139542,...,-1.629993,-0.474128,-0.121240,-1.151901,0.259121,-0.660217,1.014837,1.001098,0.818096,51
9998,0.841577,-0.533274,0.582976,-1.719419,-0.163720,0.373755,-0.131582,1.391503,-1.141439,-0.202955,...,-0.789795,0.903566,-0.133389,-1.617281,0.451151,-0.988805,0.116386,-1.195278,0.536807,42
9999,1.242993,-1.167087,0.367134,-2.756446,0.528689,-0.357787,-0.612024,0.279047,-1.584231,0.543273,...,-1.214219,-0.235788,-0.332161,-0.466116,-0.738852,0.234266,0.285805,-1.309155,0.906797,70

In [3]:
ClassLabel="Class Label"
dataFeatures_true = true.drop(ClassLabel,axis = 1).values

r=len(dataFeatures_true)
dataFeatures_true=dataFeatures_true[:r]

In [4]:
dataPhenotypes_true = true[ClassLabel].values

In [5]:
iteration=len(dataFeatures_true[0])
sample_size=len(dataFeatures_true)

In [6]:
dataPhenotypes_true= dataPhenotypes_true[:r]

# Ruleset Dataframe

In [7]:
ruleset = pd.read_csv ('RulePopulationCifar100Resnet100_XCS2.csv')

ruleset

,0,1,2,3,4,5,6,7,8,9,...,Prediction,Prediction Error,Accuracy,Numerosity,Avg Action Set Size,TimeStamp GA,Iteration Initialized,Specificity,Experience,Match Count
0,#,#,"0.0834049696000001,2.4366713044","-3.473042459225,-1.5603051467750002","-3.367927339825,1.1203749458250003",#,#,#,#,"-2.19724035483,1.54684639283",...,10,0,1,1,1,0,0,0.42,0,1
1,#,#,"-0.24343757690000012,2.7635138509",#,"-1.94557802395,-0.30197437004999994","-1.402359769445,0.615923807445",#,#,"-1.477410053325,0.03573415132500002","-1.744326635355,1.093932673355",...,10,0,1,1,1,0,0,0.55,0,1
2,"-0.16716063062499997,1.554638504625","-1.6260041112499999,0.19641174125000005","0.37756326144999997,2.1425130125500003",#,#,#,#,"-0.4201195099199999,3.81561230192","-2.093876210775,0.6522003087750001",#,...,10,0,1,1,1,0,0,0.63,0,1
3,"-1.7167798523500002,3.10425772635","-2.21560924,0.7860168700000001","-0.27612183155000003,2.7961981055500003","-3.9677159021,-1.0656317039000003","-2.103616836825,-0.14393555717499995",#,#,"0.40717185958,2.98832093242",#,#,...,10,0,1,1,1,0,0,0.55,0,1
4,#,"-2.59081250375,1.16122013375","-0.701017142,3.221093416","-4.891106328799999,-0.14224127720000057","-2.57773327545,0.33018088145000024",#,"-1.90477466321,1.73354872721",#,"-2.2900245336000005,0.8483486316000002",#,...,10,0,1,1,1,0,0,0.49,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"-0.042665887200000085,2.7122127292",#,"0.5921179052499996,4.18738591675",#,"-0.7584050528500001,1.6437849028500002",#,#,#,#,#,...,10,0,1,1,1,499,499,0.44,0,1
9996,#,#,#,#,"-1.5485991172250002,2.4339789672250003",#,"-1.2104499999300002,2.15328294593",#,#,#,...,10,0,1,1,1,499,499,0.52,0,1
9997,"0.026206078209999983,2.64334076379",#,#,#,#,#,"-0.4896500829600001,1.4324830289600001",#,"-2.1595995246250004,0.9227312626250003",#,...,10,0,1,1,1,499,499,0.47,0,1
9998,#,#,"1.0823817249999999,3.697122097","-2.764949803525,-0.06073498247500009","-1.6118146423750004,2.4971944923750002",#,#,#,#,#,...,10,0,1,1,1,499,499,0.46,0,1
9999,#,"-2.113739591625,-0.559326070375","0.036485576200000036,4.7430182458",#,#,#,"-1.89692611133,2.8397590573300002",#,"-1.7953240679500002,0.5584558059500001","-2.78294435795,-0.9712894800500002",...,10,0,1,1,1,499,499,0.52,0,1

In [8]:
ruleset2=ruleset.replace("#",np.nan)

In [9]:
ruleset3=ruleset2.replace(np.nan,0)

In [10]:
ruleset3

,0,1,2,3,4,5,6,7,8,9,...,Prediction,Prediction Error,Accuracy,Numerosity,Avg Action Set Size,TimeStamp GA,Iteration Initialized,Specificity,Experience,Match Count
0,0,0,"0.0834049696000001,2.4366713044","-3.473042459225,-1.5603051467750002","-3.367927339825,1.1203749458250003",0,0,0,0,"-2.19724035483,1.54684639283",...,10,0,1,1,1,0,0,0.42,0,1
1,0,0,"-0.24343757690000012,2.7635138509",0,"-1.94557802395,-0.30197437004999994","-1.402359769445,0.615923807445",0,0,"-1.477410053325,0.03573415132500002","-1.744326635355,1.093932673355",...,10,0,1,1,1,0,0,0.55,0,1
2,"-0.16716063062499997,1.554638504625","-1.6260041112499999,0.19641174125000005","0.37756326144999997,2.1425130125500003",0,0,0,0,"-0.4201195099199999,3.81561230192","-2.093876210775,0.6522003087750001",0,...,10,0,1,1,1,0,0,0.63,0,1
3,"-1.7167798523500002,3.10425772635","-2.21560924,0.7860168700000001","-0.27612183155000003,2.7961981055500003","-3.9677159021,-1.0656317039000003","-2.103616836825,-0.14393555717499995",0,0,"0.40717185958,2.98832093242",0,0,...,10,0,1,1,1,0,0,0.55,0,1
4,0,"-2.59081250375,1.16122013375","-0.701017142,3.221093416","-4.891106328799999,-0.14224127720000057","-2.57773327545,0.33018088145000024",0,"-1.90477466321,1.73354872721",0,"-2.2900245336000005,0.8483486316000002",0,...,10,0,1,1,1,0,0,0.49,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"-0.042665887200000085,2.7122127292",0,"0.5921179052499996,4.18738591675",0,"-0.7584050528500001,1.6437849028500002",0,0,0,0,0,...,10,0,1,1,1,499,499,0.44,0,1
9996,0,0,0,0,"-1.5485991172250002,2.4339789672250003",0,"-1.2104499999300002,2.15328294593",0,0,0,...,10,0,1,1,1,499,499,0.52,0,1
9997,"0.026206078209999983,2.64334076379",0,0,0,0,0,"-0.4896500829600001,1.4324830289600001",0,"-2.1595995246250004,0.9227312626250003",0,...,10,0,1,1,1,499,499,0.47,0,1
9998,0,0,"1.0823817249999999,3.697122097","-2.764949803525,-0.06073498247500009","-1.6118146423750004,2.4971944923750002",0,0,0,0,0,...,10,0,1,1,1,499,499,0.46,0,1
9999,0,"-2.113739591625,-0.559326070375","0.036485576200000036,4.7430182458",0,0,0,"-1.89692611133,2.8397590573300002",0,"-1.7953240679500002,0.5584558059500001","-2.78294435795,-0.9712894800500002",...,10,0,1,1,1,499,499,0.52,0,1

In [11]:
Extra=['Class Label','Fitness','Prediction','Prediction Error','Accuracy','Numerosity','Avg Action Set Size','TimeStamp GA','Iteration Initialized','Specificity','Experience','Match Count']

In [12]:
correct=Extra[10]

In [13]:
#ruleset1
#Features = ruleset.drop(Extra,axis = 1).columns.values

#ruleset2
#Features = ruleset2.drop(Extra,axis = 1).columns.values

#ruleset3
Features = ruleset3.drop(Extra,axis = 1).columns.values
Feature_count=len(Features)

print(Feature_count)
Features

100

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
       '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
       '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56',
       '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67',
       '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78',
       '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
       '90', '91', '92', '93', '94', '95', '96', '97', '98', '99'],
      dtype=object)

#New Ruleset

In [14]:
high="_high"
low="_low"

In [15]:
for x in range(0,Feature_count):

  feature_name=Features[x]

  if x==0:
    index_count_l=0
    index_count_h=1

  else:
    index_count_l=2*x
    index_count_h=index_count_l+1

  split_column=ruleset3[feature_name].str.split(',', expand=True)

  feature_name_low=feature_name+low
  feature_name_high=feature_name+high

  ruleset3.insert(index_count_l,feature_name_low,split_column[0])
  ruleset3.insert(index_count_h,feature_name_high,split_column[1])

  ruleset3=ruleset3.drop(columns=feature_name)

In [16]:
ruleset3=ruleset3.replace(np.nan,0)

In [17]:
ruleset3

,0_low,0_high,1_low,1_high,2_low,2_high,3_low,3_high,4_low,4_high,...,Prediction,Prediction Error,Accuracy,Numerosity,Avg Action Set Size,TimeStamp GA,Iteration Initialized,Specificity,Experience,Match Count
0,0,0,0,0,0.0834049696000001,2.4366713044,-3.473042459225,-1.5603051467750002,-3.367927339825,1.1203749458250003,...,10,0,1,1,1,0,0,0.42,0,1
1,0,0,0,0,-0.24343757690000012,2.7635138509,0,0,-1.94557802395,-0.30197437004999994,...,10,0,1,1,1,0,0,0.55,0,1
2,-0.16716063062499997,1.554638504625,-1.6260041112499999,0.19641174125000005,0.37756326144999997,2.1425130125500003,0,0,0,0,...,10,0,1,1,1,0,0,0.63,0,1
3,-1.7167798523500002,3.10425772635,-2.21560924,0.7860168700000001,-0.27612183155000003,2.7961981055500003,-3.9677159021,-1.0656317039000003,-2.103616836825,-0.14393555717499995,...,10,0,1,1,1,0,0,0.55,0,1
4,0,0,-2.59081250375,1.16122013375,-0.701017142,3.221093416,-4.891106328799999,-0.14224127720000057,-2.57773327545,0.33018088145000024,...,10,0,1,1,1,0,0,0.49,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.042665887200000085,2.7122127292,0,0,0.5921179052499996,4.18738591675,0,0,-0.7584050528500001,1.6437849028500002,...,10,0,1,1,1,499,499,0.44,0,1
9996,0,0,0,0,0,0,0,0,-1.5485991172250002,2.4339789672250003,...,10,0,1,1,1,499,499,0.52,0,1
9997,0.026206078209999983,2.64334076379,0,0,0,0,0,0,0,0,...,10,0,1,1,1,499,499,0.47,0,1
9998,0,0,0,0,1.0823817249999999,3.697122097,-2.764949803525,-0.06073498247500009,-1.6118146423750004,2.4971944923750002,...,10,0,1,1,1,499,499,0.46,0,1
9999,0,0,-2.113739591625,-0.559326070375,0.036485576200000036,4.7430182458,0,0,0,0,...,10,0,1,1,1,499,499,0.52,0,1

In [18]:
Features_1 = ruleset3.drop(Extra,axis = 1).columns.values
Features_1

array(['0_low', '0_high', '1_low', '1_high', '2_low', '2_high', '3_low',
       '3_high', '4_low', '4_high', '5_low', '5_high', '6_low', '6_high',
       '7_low', '7_high', '8_low', '8_high', '9_low', '9_high', '10_low',
       '10_high', '11_low', '11_high', '12_low', '12_high', '13_low',
       '13_high', '14_low', '14_high', '15_low', '15_high', '16_low',
       '16_high', '17_low', '17_high', '18_low', '18_high', '19_low',
       '19_high', '20_low', '20_high', '21_low', '21_high', '22_low',
       '22_high', '23_low', '23_high', '24_low', '24_high', '25_low',
       '25_high', '26_low', '26_high', '27_low', '27_high', '28_low',
       '28_high', '29_low', '29_high', '30_low', '30_high', '31_low',
       '31_high', '32_low', '32_high', '33_low', '33_high', '34_low',
       '34_high', '35_low', '35_high', '36_low', '36_high', '37_low',
       '37_high', '38_low', '38_high', '39_low', '39_high', '40_low',
       '40_high', '41_low', '41_high', '42_low', '42_high', '43_low',
       '43_high', '44_low', '44_high', '45_low', '45_high', '46_low',
       '46_high', '47_low', '47_high', '48_low', '48_high', '49_low',
       '49_high', '50_low', '50_high', '51_low', '51_high', '52_low',
       '52_high', '53_low', '53_high', '54_low', '54_high', '55_low',
       '55_high', '56_low', '56_high', '57_low', '57_high', '58_low',
       '58_high', '59_low', '59_high', '60_low', '60_high', '61_low',
       '61_high', '62_low', '62_high', '63_low', '63_high', '64_low',
       '64_high', '65_low', '65_high', '66_low', '66_high', '67_low',
       '67_high', '68_low', '68_high', '69_low', '69_high', '70_low',
       '70_high', '71_low', '71_high', '72_low', '72_high', '73_low',
       '73_high', '74_low', '74_high', '75_low', '75_high', '76_low',
       '76_high', '77_low', '77_high', '78_low', '78_high', '79_low',
       '79_high', '80_low', '80_high', '81_low', '81_high', '82_low',
       '82_high', '83_low', '83_high', '84_low', '84_high', '85_low',
       '85_high', '86_low', '86_high', '87_low', '87_high', '88_low',
       '88_high', '89_low', '89_high', '90_low', '90_high', '91_low',
       '91_high', '92_low', '92_high', '93_low', '93_high', '94_low',
       '94_high', '95_low', '95_high', '96_low', '96_high', '97_low',
       '97_high', '98_low', '98_high', '99_low', '99_high'], dtype=object)

#code

In [19]:
#number of classes
class_number=100

#enter first part of the file name here

#Google colab example: '/content/first part of file name_'
#first_part='/content/Vgg19_cifar10_100_shared_class_'

#non google colab:'first part of file name
first_part='Resnet_cifar100_100_shared_class_'

#last part of file name
incorrect='_incorrect.csv'
instance_list=[]

In [20]:
for x in range(0,class_number):
  number=str(x)
  file=first_part+number+incorrect
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  instance_list.append(a)

In [21]:
dataFeatures_true[0]

array([-1.60710171e-01, -1.18609078e-01,  1.36418164e+00, -3.32520771e+00,
       -1.51964903e+00,  4.55779463e-01, -2.36836624e+00,  7.11584330e-01,
       -1.01551890e+00, -5.40396452e-01, -4.97346371e-01, -9.23889756e-01,
       -2.76280135e-01, -8.23558807e-01, -2.91256220e-02, -2.26159000e+00,
       -8.46617639e-01,  2.15681577e+00, -3.50168347e-01,  6.42213345e-01,
       -2.80791014e-01,  4.43139780e-02,  4.05199945e-01, -8.65612805e-01,
        4.11640465e-01, -3.11364436e+00,  9.43492770e-01, -1.36548972e+00,
        4.90468979e-01,  1.04445875e-01, -8.03751349e-01, -1.84903666e-01,
        2.24562466e-01, -4.70722586e-01,  8.81080151e-01, -2.49035612e-01,
       -1.29931605e+00,  7.18930602e-01,  1.60863614e+00, -1.22483984e-01,
       -1.78463996e+00,  1.43211770e+00, -8.69011462e-01,  1.23421061e+00,
       -1.12371409e+00, -3.55871379e-01,  7.99297094e-01, -2.32474536e-01,
       -2.72576547e+00,  1.23034286e+00, -8.02388310e-01, -4.61649001e-01,
        2.16970712e-01, -1.02133143e+00,  6.16893470e-01,  1.49965584e-01,
       -1.56322002e-01, -1.87505925e+00,  1.32499814e+00, -1.46460581e+00,
       -1.66560817e+00, -4.45097148e-01,  1.61313906e-01,  1.50518012e+00,
       -2.77746900e-03, -2.10309720e+00, -1.06422655e-01,  1.34044206e+00,
       -2.65790844e+00,  6.16227090e-01,  5.90493262e-01,  1.77615130e+00,
       -3.82500201e-01, -1.31967974e+00,  1.36765301e-01, -1.92578089e+00,
        1.78902492e-01,  2.08422661e+00, -1.12423170e+00,  5.41190147e-01,
       -3.04643899e-01, -7.43412316e-01,  5.22063553e-01,  1.03920603e+00,
       -1.50206780e+00,  1.70575166e+00,  2.66021681e+00,  4.12276119e-01,
        3.51643533e-01,  9.96806681e-01,  4.59474981e-01, -9.97015238e-01,
       -4.32137161e-01,  1.80447640e-02, -7.01093793e-01, -2.33964026e-01,
       -7.22853959e-01,  8.57195318e-01, -1.50231326e+00,  9.09890294e-01])

In [22]:
for feature in range(iteration):
  print(feature)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [23]:
incorrect_count_list=[]
ml='_XCS'

for x in range(0,class_number):

  incorrect_count=0

  #new class list
  b=instance_list[x]
  

  for y in b:

    #instance for class
    z=y[0]

    #filter ruleset by class
    class_check=dataPhenotypes_true[z-1]
    ruleset_filter= ruleset3[ruleset3['Class Label'] == class_check]
    
    #converts string to float
    ruleset_filter2=ruleset_filter.astype(float)


    #Checks feature for each rule in class
    for feature in range(iteration):
      f=dataFeatures_true[z-1][feature]

      #lowest range for feature
      l=2*feature

      #highest range for feature
      h=l+1

      #low feature name
      Low=Features_1[l]

      #high feature name
      High=Features_1[h]

      #when the count starts at 0
      if feature==0:
        ruleset_filter_test= ruleset_filter2[((ruleset_filter2[Low] < f)&(ruleset_filter2[High] >= f)) | (ruleset_filter2[High] == 0) ]
      
      #when the feature count is not 0
      else:
        ruleset_filter_test= ruleset_filter_test[((ruleset_filter_test[Low] < f)&(ruleset_filter_test[High] >= f)) | (ruleset_filter_test[High] == 0) ]
    
    #filters out all of the rows that have a correct count of zero
    ruleset_filter_test2= ruleset_filter_test[ruleset_filter_test[correct] != 0 ]

    #replaces 0 with #
    ruleset_filter_test3=ruleset_filter_test2.replace(0,'#')

    #adds
    if ruleset_filter_test3.empty:
      continue
    else:
      file_2=str(iteration)+'_class_'+str(class_check)+'_iteration_'+str(z)+'_'+ml+'.csv'
      ruleset_filter_test3.to_csv(file_2, index=False) 
      #files.download(file_2)
      incorrect_count+=1
    
  incorrect_count_list.append(incorrect_count)

In [24]:
incorrect_count_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0]

In [25]:
correct_csv='_correct.csv'

In [26]:
mimic=[]

for x in range(0,class_number):
  number=str(x)
  file=first_part+number+correct_csv
  instances = pd.read_csv (file)
  a=instances.values.tolist()
  b=len(a)
  total=b+incorrect_count_list[x]
  score=total/sample_size
  mimic.append(score)

In [27]:
mimic

[0.9858,
 0.9851,
 0.987,
 0.9853,
 0.9855,
 0.9856,
 0.9869,
 0.9855,
 0.9881,
 0.9849,
 0.987,
 0.9878,
 0.9869,
 0.9869,
 0.9873,
 0.9872,
 0.9857,
 0.9871,
 0.9868,
 0.9883,
 0.9875,
 0.9868,
 0.9871,
 0.9871,
 0.9869,
 0.988,
 0.9872,
 0.9855,
 0.9868,
 0.9873,
 0.985,
 0.9861,
 0.9873,
 0.9864,
 0.9874,
 0.9868,
 0.9858,
 0.989,
 0.9855,
 0.9855,
 0.9876,
 0.9852,
 0.986,
 0.9873,
 0.987,
 0.9882,
 0.9873,
 0.9867,
 0.9862,
 0.9871,
 0.9863,
 0.987,
 0.9866,
 0.9855,
 0.9863,
 0.987,
 0.985,
 0.986,
 0.9879,
 0.9874,
 0.9829,
 0.9839,
 0.9865,
 0.9869,
 0.9878,
 0.9839,
 0.9866,
 0.9861,
 0.9865,
 0.9888,
 0.9878,
 0.9836,
 0.9867,
 0.9853,
 0.9879,
 0.9862,
 0.9879,
 0.9884,
 0.9866,
 0.9874,
 0.9835,
 0.9872,
 0.9858,
 0.9869,
 0.9871,
 0.985,
 0.986,
 0.9848,
 0.9854,
 0.9876,
 0.986,
 0.9872,
 0.9866,
 0.9883,
 0.9869,
 0.9884,
 0.9861,
 0.9846,
 0.9861,
 0.9867]

In [28]:
average=sum(mimic)/class_number
average

0.9865319999999997